// To run these tests, ensure you have the following dev dependencies in pubspec.yaml:
//   bloc_test: ^9.1.0
//   mockito: ^5.4.0
// Run: flutter pub add --dev bloc_test mockito

import 'package:flutter_test/flutter_test.dart';
import 'package:bloc_test/bloc_test.dart';
import 'package:mockito/mockito.dart';
import 'package:mockito/annotations.dart';
import 'package:ai_therapist_app/blocs/chat_bloc.dart';
import 'package:ai_therapist_app/services/groq_service.dart';
import 'chat_bloc_test.mocks.dart'; // Generated by build_runner

// If chat_bloc_test.mocks.dart does not exist, run:
// flutter pub run build_runner build

@GenerateMocks([GroqService])
void main() {
  group('ChatBloc', () {
    late MockGroqService mockGroqService;
    late ChatBloc chatBloc;

    setUp(() {
      mockGroqService = MockGroqService();
      chatBloc = ChatBloc(groqService: mockGroqService);
    });

    tearDown(() async {
      await chatBloc.close();
    });

    blocTest<ChatBloc, ChatState>(
      'emits [ChatLoading, ChatLoaded, ChatCompletedState] for successful stream',
      build: () {
        when(mockGroqService.streamChatCompletionViaWebSocket(
          message: anyNamed('message'),
          history: anyNamed('history'),
          sessionId: anyNamed('sessionId'),
        )).thenAnswer((_) => Stream.fromIterable([
              {'type': 'chunk', 'content': 'Hello'},
              {'type': 'done'},
            ]));
        return chatBloc;
      },
      act: (bloc) => bloc.add(
          StartChat(message: '', history: const [], sessionId: 'test-session')),
      expect: () => [
        ChatLoading(),
        ChatLoaded(['Hello']),
        ChatCompletedState(),
      ],
    );
  });
}
