// Mocks generated by Mockito 5.4.6 from annotations
// in ai_therapist_app/test/blocs/chat_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:ai_therapist_app/services/groq_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GroqService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGroqService extends _i1.Mock implements _i2.GroqService {
  MockGroqService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isConfigured => (super.noSuchMethod(
        Invocation.getter(#isConfigured),
        returnValue: false,
      ) as bool);

  @override
  String get llmModelId => (super.noSuchMethod(
        Invocation.getter(#llmModelId),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#llmModelId),
        ),
      ) as String);

  @override
  set sessionId(String? value) => super.noSuchMethod(
        Invocation.setter(
          #sessionId,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void resetConversationMemory() => super.noSuchMethod(
        Invocation.method(
          #resetConversationMemory,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setAvailable(bool? available) => super.noSuchMethod(
        Invocation.method(
          #setAvailable,
          [available],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<String> generateChatCompletion({
    required String? userMessage,
    String? systemPrompt = '',
    String? model,
    double? temperature = 0.7,
    int? maxTokens = 1000,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateChatCompletion,
          [],
          {
            #userMessage: userMessage,
            #systemPrompt: systemPrompt,
            #model: model,
            #temperature: temperature,
            #maxTokens: maxTokens,
          },
        ),
        returnValue: _i4.Future<String>.value(_i3.dummyValue<String>(
          this,
          Invocation.method(
            #generateChatCompletion,
            [],
            {
              #userMessage: userMessage,
              #systemPrompt: systemPrompt,
              #model: model,
              #temperature: temperature,
              #maxTokens: maxTokens,
            },
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<Map<String, dynamic>> testConnection() => (super.noSuchMethod(
        Invocation.method(
          #testConnection,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Stream<Map<String, dynamic>> streamChatCompletionViaWebSocket({
    required String? message,
    List<Map<String, dynamic>>? history = const [],
    String? sessionId,
    int? maxRetries = 3,
    Duration? retryDelay = const Duration(seconds: 2),
    Duration? inactivityTimeout = const Duration(seconds: 30),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamChatCompletionViaWebSocket,
          [],
          {
            #message: message,
            #history: history,
            #sessionId: sessionId,
            #maxRetries: maxRetries,
            #retryDelay: retryDelay,
            #inactivityTimeout: inactivityTimeout,
          },
        ),
        returnValue: _i4.Stream<Map<String, dynamic>>.empty(),
      ) as _i4.Stream<Map<String, dynamic>>);
}
