// Mocks generated by Mockito 5.4.6 from annotations
// in ai_therapist_app/test/blocs/voice_session_bloc_characterization_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:typed_data' as _i17;
import 'dart:ui' as _i8;

import 'package:ai_therapist_app/di/interfaces/i_navigation_service.dart'
    as _i20;
import 'package:ai_therapist_app/di/interfaces/i_progress_service.dart' as _i18;
import 'package:ai_therapist_app/di/interfaces/i_therapy_service.dart' as _i14;
import 'package:ai_therapist_app/di/interfaces/i_voice_service.dart' as _i16;
import 'package:ai_therapist_app/models/therapy_message.dart' as _i5;
import 'package:ai_therapist_app/models/user_profile.dart' as _i15;
import 'package:ai_therapist_app/models/user_progress.dart' as _i6;
import 'package:ai_therapist_app/services/audio_player_manager.dart' as _i3;
import 'package:ai_therapist_app/services/auto_listening_coordinator.dart'
    as _i2;
import 'package:ai_therapist_app/services/base_voice_service.dart' as _i11;
import 'package:ai_therapist_app/services/recording_manager.dart' as _i4;
import 'package:ai_therapist_app/services/vad_manager.dart' as _i13;
import 'package:ai_therapist_app/services/voice_service.dart' as _i9;
import 'package:ai_therapist_app/widgets/mood_selector.dart' as _i19;
import 'package:flutter/foundation.dart' as _i7;
import 'package:just_audio/just_audio.dart' as _i21;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAutoListeningCoordinator_0 extends _i1.SmartFake
    implements _i2.AutoListeningCoordinator {
  _FakeAutoListeningCoordinator_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAudioPlayerManager_1 extends _i1.SmartFake
    implements _i3.AudioPlayerManager {
  _FakeAudioPlayerManager_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRecordingManager_2 extends _i1.SmartFake
    implements _i4.RecordingManager {
  _FakeRecordingManager_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTherapyMessage_3 extends _i1.SmartFake
    implements _i5.TherapyMessage {
  _FakeTherapyMessage_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserProgress_4 extends _i1.SmartFake implements _i6.UserProgress {
  _FakeUserProgress_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeValueNotifier_5<T> extends _i1.SmartFake
    implements _i7.ValueNotifier<T> {
  _FakeValueNotifier_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeColor_6 extends _i1.SmartFake implements _i8.Color {
  _FakeColor_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [VoiceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockVoiceService extends _i1.Mock implements _i9.VoiceService {
  MockVoiceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAiSpeaking => (super.noSuchMethod(
        Invocation.getter(#isAiSpeaking),
        returnValue: false,
      ) as bool);

  @override
  _i10.Stream<_i11.RecordingState> get recordingState => (super.noSuchMethod(
        Invocation.getter(#recordingState),
        returnValue: _i10.Stream<_i11.RecordingState>.empty(),
      ) as _i10.Stream<_i11.RecordingState>);

  @override
  String get apiUrl => (super.noSuchMethod(
        Invocation.getter(#apiUrl),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.getter(#apiUrl),
        ),
      ) as String);

  @override
  _i10.Stream<bool> get audioPlaybackStream => (super.noSuchMethod(
        Invocation.getter(#audioPlaybackStream),
        returnValue: _i10.Stream<bool>.empty(),
      ) as _i10.Stream<bool>);

  @override
  _i10.Stream<bool> get isTtsActuallySpeaking => (super.noSuchMethod(
        Invocation.getter(#isTtsActuallySpeaking),
        returnValue: _i10.Stream<bool>.empty(),
      ) as _i10.Stream<bool>);

  @override
  _i10.Stream<_i2.AutoListeningState> get autoListeningStateStream =>
      (super.noSuchMethod(
        Invocation.getter(#autoListeningStateStream),
        returnValue: _i10.Stream<_i2.AutoListeningState>.empty(),
      ) as _i10.Stream<_i2.AutoListeningState>);

  @override
  _i10.Stream<bool> get autoListeningModeEnabledStream => (super.noSuchMethod(
        Invocation.getter(#autoListeningModeEnabledStream),
        returnValue: _i10.Stream<bool>.empty(),
      ) as _i10.Stream<bool>);

  @override
  _i2.AutoListeningCoordinator get autoListeningCoordinator =>
      (super.noSuchMethod(
        Invocation.getter(#autoListeningCoordinator),
        returnValue: _FakeAutoListeningCoordinator_0(
          this,
          Invocation.getter(#autoListeningCoordinator),
        ),
      ) as _i2.AutoListeningCoordinator);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  set isAiSpeaking(bool? _isAiSpeaking) => super.noSuchMethod(
        Invocation.setter(
          #isAiSpeaking,
          _isAiSpeaking,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<void> enableAutoMode() => (super.noSuchMethod(
        Invocation.method(
          #enableAutoMode,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> disableAutoMode() => (super.noSuchMethod(
        Invocation.method(
          #disableAutoMode,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> enableAutoModeWithAudioState(bool? isAudioPlaying) =>
      (super.noSuchMethod(
        Invocation.method(
          #enableAutoModeWithAudioState,
          [isAudioPlaying],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> initializeOnlyIfNeeded() => (super.noSuchMethod(
        Invocation.method(
          #initializeOnlyIfNeeded,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> startRecording() => (super.noSuchMethod(
        Invocation.method(
          #startRecording,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<String?> stopRecording() => (super.noSuchMethod(
        Invocation.method(
          #stopRecording,
          [],
        ),
        returnValue: _i10.Future<String?>.value(),
      ) as _i10.Future<String?>);

  @override
  _i10.Future<String> processRecordedAudioFile(String? recordedFilePath) =>
      (super.noSuchMethod(
        Invocation.method(
          #processRecordedAudioFile,
          [recordedFilePath],
        ),
        returnValue: _i10.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #processRecordedAudioFile,
            [recordedFilePath],
          ),
        )),
      ) as _i10.Future<String>);

  @override
  _i10.Future<void> playAudio(String? audioPath) => (super.noSuchMethod(
        Invocation.method(
          #playAudio,
          [audioPath],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> stopAudio() => (super.noSuchMethod(
        Invocation.method(
          #stopAudio,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> playStreamingAudio(String? audioUrl) => (super.noSuchMethod(
        Invocation.method(
          #playStreamingAudio,
          [audioUrl],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<bool> isPlaying() => (super.noSuchMethod(
        Invocation.method(
          #isPlaying,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.AudioPlayerManager getAudioPlayerManager() => (super.noSuchMethod(
        Invocation.method(
          #getAudioPlayerManager,
          [],
        ),
        returnValue: _FakeAudioPlayerManager_1(
          this,
          Invocation.method(
            #getAudioPlayerManager,
            [],
          ),
        ),
      ) as _i3.AudioPlayerManager);

  @override
  _i4.RecordingManager getRecordingManager() => (super.noSuchMethod(
        Invocation.method(
          #getRecordingManager,
          [],
        ),
        returnValue: _FakeRecordingManager_2(
          this,
          Invocation.method(
            #getRecordingManager,
            [],
          ),
        ),
      ) as _i4.RecordingManager);

  @override
  _i10.Future<void> playAudioWithCallbacks(
    String? filePath, {
    void Function()? onDone,
    void Function(String)? onError,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #playAudioWithCallbacks,
          [filePath],
          {
            #onDone: onDone,
            #onError: onError,
          },
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  void updateTTSSpeakingState(bool? isSpeaking) => super.noSuchMethod(
        Invocation.method(
          #updateTTSSpeakingState,
          [isSpeaking],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<void> pauseVAD() => (super.noSuchMethod(
        Invocation.method(
          #pauseVAD,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> resumeVAD() => (super.noSuchMethod(
        Invocation.method(
          #resumeVAD,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  void resetTTSState() => super.noSuchMethod(
        Invocation.method(
          #resetTTSState,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<void> setSpeakerMuted(bool? muted) => (super.noSuchMethod(
        Invocation.method(
          #setSpeakerMuted,
          [muted],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}

/// A class which mocks [VADManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockVADManager extends _i1.Mock implements _i13.VADManager {
  MockVADManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Stream<void> get onSpeechStart => (super.noSuchMethod(
        Invocation.getter(#onSpeechStart),
        returnValue: _i10.Stream<void>.empty(),
      ) as _i10.Stream<void>);

  @override
  _i10.Stream<void> get onSpeechEnd => (super.noSuchMethod(
        Invocation.getter(#onSpeechEnd),
        returnValue: _i10.Stream<void>.empty(),
      ) as _i10.Stream<void>);

  @override
  _i10.Stream<String> get onError => (super.noSuchMethod(
        Invocation.getter(#onError),
        returnValue: _i10.Stream<String>.empty(),
      ) as _i10.Stream<String>);

  @override
  _i10.Stream<double> get amplitudeStream => (super.noSuchMethod(
        Invocation.getter(#amplitudeStream),
        returnValue: _i10.Stream<double>.empty(),
      ) as _i10.Stream<double>);

  @override
  _i10.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<bool> startListening() => (super.noSuchMethod(
        Invocation.method(
          #startListening,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<void> stopListening() => (super.noSuchMethod(
        Invocation.method(
          #stopListening,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  void resetCalibration() => super.noSuchMethod(
        Invocation.method(
          #resetCalibration,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> getNoiseInfo() => (super.noSuchMethod(
        Invocation.method(
          #getNoiseInfo,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i10.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}

/// A class which mocks [ITherapyService].
///
/// See the documentation for Mockito's code generation for more information.
class MockITherapyService extends _i1.Mock implements _i14.ITherapyService {
  MockITherapyService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i10.Future<String> startSession({
    required String? userId,
    String? sessionType,
    Map<String, dynamic>? initialContext,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startSession,
          [],
          {
            #userId: userId,
            #sessionType: sessionType,
            #initialContext: initialContext,
          },
        ),
        returnValue: _i10.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #startSession,
            [],
            {
              #userId: userId,
              #sessionType: sessionType,
              #initialContext: initialContext,
            },
          ),
        )),
      ) as _i10.Future<String>);

  @override
  _i10.Future<void> endSession(String? sessionId) => (super.noSuchMethod(
        Invocation.method(
          #endSession,
          [sessionId],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> pauseSession(String? sessionId) => (super.noSuchMethod(
        Invocation.method(
          #pauseSession,
          [sessionId],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> resumeSession(String? sessionId) => (super.noSuchMethod(
        Invocation.method(
          #resumeSession,
          [sessionId],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i5.TherapyMessage> processMessage({
    required String? sessionId,
    required String? userMessage,
    Map<String, dynamic>? context,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #processMessage,
          [],
          {
            #sessionId: sessionId,
            #userMessage: userMessage,
            #context: context,
          },
        ),
        returnValue:
            _i10.Future<_i5.TherapyMessage>.value(_FakeTherapyMessage_3(
          this,
          Invocation.method(
            #processMessage,
            [],
            {
              #sessionId: sessionId,
              #userMessage: userMessage,
              #context: context,
            },
          ),
        )),
      ) as _i10.Future<_i5.TherapyMessage>);

  @override
  _i10.Future<String> generateResponse({
    required String? sessionId,
    required String? userMessage,
    Map<String, dynamic>? context,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateResponse,
          [],
          {
            #sessionId: sessionId,
            #userMessage: userMessage,
            #context: context,
          },
        ),
        returnValue: _i10.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #generateResponse,
            [],
            {
              #sessionId: sessionId,
              #userMessage: userMessage,
              #context: context,
            },
          ),
        )),
      ) as _i10.Future<String>);

  @override
  _i10.Future<void> updateSessionContext(
    String? sessionId,
    Map<String, dynamic>? context,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSessionContext,
          [
            sessionId,
            context,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<Map<String, dynamic>?> getSessionContext(String? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSessionContext,
          [sessionId],
        ),
        returnValue: _i10.Future<Map<String, dynamic>?>.value(),
      ) as _i10.Future<Map<String, dynamic>?>);

  @override
  _i10.Future<List<_i5.TherapyMessage>> getConversationHistory(
          String? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getConversationHistory,
          [sessionId],
        ),
        returnValue:
            _i10.Future<List<_i5.TherapyMessage>>.value(<_i5.TherapyMessage>[]),
      ) as _i10.Future<List<_i5.TherapyMessage>>);

  @override
  _i10.Future<void> saveMessage(
    String? sessionId,
    _i5.TherapyMessage? message,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveMessage,
          [
            sessionId,
            message,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setTherapyStyle(
    String? sessionId,
    String? therapyStyle,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setTherapyStyle,
          [
            sessionId,
            therapyStyle,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> updateTherapyGoals(
    String? sessionId,
    List<String>? goals,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTherapyGoals,
          [
            sessionId,
            goals,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> updateUserProfile(_i15.UserProfile? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserProfile,
          [profile],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i15.UserProfile?> getUserProfile(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [userId],
        ),
        returnValue: _i10.Future<_i15.UserProfile?>.value(),
      ) as _i10.Future<_i15.UserProfile?>);

  @override
  _i10.Future<Map<String, dynamic>> getSessionSummary(String? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSessionSummary,
          [sessionId],
        ),
        returnValue:
            _i10.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<List<String>> getActionItems(String? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActionItems,
          [sessionId],
        ),
        returnValue: _i10.Future<List<String>>.value(<String>[]),
      ) as _i10.Future<List<String>>);

  @override
  _i10.Future<bool> detectCrisis(String? message) => (super.noSuchMethod(
        Invocation.method(
          #detectCrisis,
          [message],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<Map<String, dynamic>> getCrisisResources() => (super.noSuchMethod(
        Invocation.method(
          #getCrisisResources,
          [],
        ),
        returnValue:
            _i10.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<void> trackMoodChange(
    String? sessionId,
    String? mood,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #trackMoodChange,
          [
            sessionId,
            mood,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<Map<String, dynamic>> getProgressMetrics(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProgressMetrics,
          [userId],
        ),
        returnValue:
            _i10.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<Map<String, dynamic>> processUserMessageWithStreamingAudio(
    String? userMessage,
    List<Map<String, String>>? history, {
    required _i10.Future<void> Function()? onTTSPlaybackComplete,
    required void Function(String)? onTTSError,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #processUserMessageWithStreamingAudio,
          [
            userMessage,
            history,
          ],
          {
            #onTTSPlaybackComplete: onTTSPlaybackComplete,
            #onTTSError: onTTSError,
          },
        ),
        returnValue:
            _i10.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<String> processUserMessage(
    String? userMessage, {
    List<Map<String, String>>? history,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #processUserMessage,
          [userMessage],
          {#history: history},
        ),
        returnValue: _i10.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #processUserMessage,
            [userMessage],
            {#history: history},
          ),
        )),
      ) as _i10.Future<String>);

  @override
  _i10.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setTherapistStyle(String? systemPrompt) => super.noSuchMethod(
        Invocation.method(
          #setTherapistStyle,
          [systemPrompt],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<Map<String, dynamic>> endSessionWithMessages(
    List<Map<String, dynamic>>? messages, {
    String? sessionTitle,
    int? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #endSessionWithMessages,
          [messages],
          {
            #sessionTitle: sessionTitle,
            #userId: userId,
          },
        ),
        returnValue:
            _i10.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i10.Future<Map<String, dynamic>>);
}

/// A class which mocks [IVoiceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIVoiceService extends _i1.Mock implements _i16.IVoiceService {
  MockIVoiceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isRecording => (super.noSuchMethod(
        Invocation.getter(#isRecording),
        returnValue: false,
      ) as bool);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i10.Stream<double> get audioLevelStream => (super.noSuchMethod(
        Invocation.getter(#audioLevelStream),
        returnValue: _i10.Stream<double>.empty(),
      ) as _i10.Stream<double>);

  @override
  bool get isPlaying => (super.noSuchMethod(
        Invocation.getter(#isPlaying),
        returnValue: false,
      ) as bool);

  @override
  _i10.Stream<bool> get isTtsActuallySpeaking => (super.noSuchMethod(
        Invocation.getter(#isTtsActuallySpeaking),
        returnValue: _i10.Stream<bool>.empty(),
      ) as _i10.Stream<bool>);

  @override
  bool get isConnectedToBackend => (super.noSuchMethod(
        Invocation.getter(#isConnectedToBackend),
        returnValue: false,
      ) as bool);

  @override
  _i10.Future<void> startRecording() => (super.noSuchMethod(
        Invocation.method(
          #startRecording,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<String> stopRecording() => (super.noSuchMethod(
        Invocation.method(
          #stopRecording,
          [],
        ),
        returnValue: _i10.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #stopRecording,
            [],
          ),
        )),
      ) as _i10.Future<String>);

  @override
  _i10.Future<void> pauseRecording() => (super.noSuchMethod(
        Invocation.method(
          #pauseRecording,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> resumeRecording() => (super.noSuchMethod(
        Invocation.method(
          #resumeRecording,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> cancelRecording() => (super.noSuchMethod(
        Invocation.method(
          #cancelRecording,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> playAudio(String? audioPath) => (super.noSuchMethod(
        Invocation.method(
          #playAudio,
          [audioPath],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> stopPlayback() => (super.noSuchMethod(
        Invocation.method(
          #stopPlayback,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> stopAudio() => (super.noSuchMethod(
        Invocation.method(
          #stopAudio,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> pausePlayback() => (super.noSuchMethod(
        Invocation.method(
          #pausePlayback,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> resumePlayback() => (super.noSuchMethod(
        Invocation.method(
          #resumePlayback,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<String> generateSpeech(
    String? text, {
    String? voice = 'alloy',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateSpeech,
          [text],
          {#voice: voice},
        ),
        returnValue: _i10.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #generateSpeech,
            [text],
            {#voice: voice},
          ),
        )),
      ) as _i10.Future<String>);

  @override
  _i10.Future<void> speakText(
    String? text, {
    String? voice = 'alloy',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #speakText,
          [text],
          {#voice: voice},
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> stopSpeaking() => (super.noSuchMethod(
        Invocation.method(
          #stopSpeaking,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  void updateTTSSpeakingState(bool? isSpeaking) => super.noSuchMethod(
        Invocation.method(
          #updateTTSSpeakingState,
          [isSpeaking],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resetTTSState() => super.noSuchMethod(
        Invocation.method(
          #resetTTSState,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<_i17.Uint8List?> processAudioWithRNNoise(
          _i17.Uint8List? audioData) =>
      (super.noSuchMethod(
        Invocation.method(
          #processAudioWithRNNoise,
          [audioData],
        ),
        returnValue: _i10.Future<_i17.Uint8List?>.value(),
      ) as _i10.Future<_i17.Uint8List?>);

  @override
  _i10.Future<String> processRecordedAudioFile(String? audioPath) =>
      (super.noSuchMethod(
        Invocation.method(
          #processRecordedAudioFile,
          [audioPath],
        ),
        returnValue: _i10.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #processRecordedAudioFile,
            [audioPath],
          ),
        )),
      ) as _i10.Future<String>);

  @override
  _i10.Future<void> connectToBackend() => (super.noSuchMethod(
        Invocation.method(
          #connectToBackend,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> disconnectFromBackend() => (super.noSuchMethod(
        Invocation.method(
          #disconnectFromBackend,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> streamAudio(_i17.Uint8List? audioData) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamAudio,
          [audioData],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> startSession(String? sessionId) => (super.noSuchMethod(
        Invocation.method(
          #startSession,
          [sessionId],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> endSession() => (super.noSuchMethod(
        Invocation.method(
          #endSession,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  void setAudioQuality(String? quality) => super.noSuchMethod(
        Invocation.method(
          #setAudioQuality,
          [quality],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setVoiceSettings(Map<String, dynamic>? settings) => super.noSuchMethod(
        Invocation.method(
          #setVoiceSettings,
          [settings],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSpeakerMuted(bool? isMuted) => super.noSuchMethod(
        Invocation.method(
          #setSpeakerMuted,
          [isMuted],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<void> enableAutoMode() => (super.noSuchMethod(
        Invocation.method(
          #enableAutoMode,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> disableAutoMode() => (super.noSuchMethod(
        Invocation.method(
          #disableAutoMode,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> initializeOnlyIfNeeded() => (super.noSuchMethod(
        Invocation.method(
          #initializeOnlyIfNeeded,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<void> cleanupTempFiles() => (super.noSuchMethod(
        Invocation.method(
          #cleanupTempFiles,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<String> getAudioUrl(String? audioPath) => (super.noSuchMethod(
        Invocation.method(
          #getAudioUrl,
          [audioPath],
        ),
        returnValue: _i10.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #getAudioUrl,
            [audioPath],
          ),
        )),
      ) as _i10.Future<String>);
}

/// A class which mocks [IProgressService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIProgressService extends _i1.Mock implements _i18.IProgressService {
  MockIProgressService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.UserProgress get progress => (super.noSuchMethod(
        Invocation.getter(#progress),
        returnValue: _FakeUserProgress_4(
          this,
          Invocation.getter(#progress),
        ),
      ) as _i6.UserProgress);

  @override
  _i7.ValueNotifier<_i6.UserProgress> get progressChanged =>
      (super.noSuchMethod(
        Invocation.getter(#progressChanged),
        returnValue: _FakeValueNotifier_5<_i6.UserProgress>(
          this,
          Invocation.getter(#progressChanged),
        ),
      ) as _i7.ValueNotifier<_i6.UserProgress>);

  @override
  bool get moodLogLimitReached => (super.noSuchMethod(
        Invocation.getter(#moodLogLimitReached),
        returnValue: false,
      ) as bool);

  @override
  _i10.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  double getConsistencyRate() => (super.noSuchMethod(
        Invocation.method(
          #getConsistencyRate,
          [],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  String getConsistencyStatus() => (super.noSuchMethod(
        Invocation.method(
          #getConsistencyStatus,
          [],
        ),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #getConsistencyStatus,
            [],
          ),
        ),
      ) as String);

  @override
  _i8.Color getConsistencyColor() => (super.noSuchMethod(
        Invocation.method(
          #getConsistencyColor,
          [],
        ),
        returnValue: _FakeColor_6(
          this,
          Invocation.method(
            #getConsistencyColor,
            [],
          ),
        ),
      ) as _i8.Color);

  @override
  int getProgressMetric(String? metric) => (super.noSuchMethod(
        Invocation.method(
          #getProgressMetric,
          [metric],
        ),
        returnValue: 0,
      ) as int);

  @override
  _i10.Future<void> updateProgressMetric(
    String? metric,
    int? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProgressMetric,
          [
            metric,
            value,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> incrementProgressMetric(
    String? metric, [
    int? amount = 1,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #incrementProgressMetric,
          [
            metric,
            amount,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<bool> logMood(
    _i19.Mood? mood, [
    String? notes,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #logMood,
          [
            mood,
            notes,
          ],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  Map<String, List<Map<String, dynamic>>> getMoodHistory({
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMoodHistory,
          [],
          {
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue: <String, List<Map<String, dynamic>>>{},
      ) as Map<String, List<Map<String, dynamic>>>);

  @override
  List<MapEntry<DateTime, int>> getMoodDataForLastDays(int? days) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMoodDataForLastDays,
          [days],
        ),
        returnValue: <MapEntry<DateTime, int>>[],
      ) as List<MapEntry<DateTime, int>>);

  @override
  _i10.Future<void> logSession(int? sessionDuration) => (super.noSuchMethod(
        Invocation.method(
          #logSession,
          [sessionDuration],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  List<MapEntry<DateTime, int>> getSessionDataForLastDays(int? days) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSessionDataForLastDays,
          [days],
        ),
        returnValue: <MapEntry<DateTime, int>>[],
      ) as List<MapEntry<DateTime, int>>);

  @override
  _i10.Future<void> resetProgress() => (super.noSuchMethod(
        Invocation.method(
          #resetProgress,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}

/// A class which mocks [INavigationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockINavigationService extends _i1.Mock
    implements _i20.INavigationService {
  MockINavigationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Stream<bool> get bottomNavVisibilityStream => (super.noSuchMethod(
        Invocation.getter(#bottomNavVisibilityStream),
        returnValue: _i10.Stream<bool>.empty(),
      ) as _i10.Stream<bool>);

  @override
  bool get isBottomNavVisible => (super.noSuchMethod(
        Invocation.getter(#isBottomNavVisible),
        returnValue: false,
      ) as bool);

  @override
  void showBottomNav() => super.noSuchMethod(
        Invocation.method(
          #showBottomNav,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void hideBottomNav() => super.noSuchMethod(
        Invocation.method(
          #hideBottomNav,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AudioPlayerManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioPlayer extends _i1.Mock implements _i3.AudioPlayerManager {
  MockAudioPlayer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Stream<bool> get isPlayingStream => (super.noSuchMethod(
        Invocation.getter(#isPlayingStream),
        returnValue: _i10.Stream<bool>.empty(),
      ) as _i10.Stream<bool>);

  @override
  _i10.Stream<String?> get errorStream => (super.noSuchMethod(
        Invocation.getter(#errorStream),
        returnValue: _i10.Stream<String?>.empty(),
      ) as _i10.Stream<String?>);

  @override
  _i10.Stream<int> get queueLengthStream => (super.noSuchMethod(
        Invocation.getter(#queueLengthStream),
        returnValue: _i10.Stream<int>.empty(),
      ) as _i10.Stream<int>);

  @override
  _i10.Stream<String?> get nowPlayingStream => (super.noSuchMethod(
        Invocation.getter(#nowPlayingStream),
        returnValue: _i10.Stream<String?>.empty(),
      ) as _i10.Stream<String?>);

  @override
  _i10.Stream<_i21.ProcessingState> get processingStateStream =>
      (super.noSuchMethod(
        Invocation.getter(#processingStateStream),
        returnValue: _i10.Stream<_i21.ProcessingState>.empty(),
      ) as _i10.Stream<_i21.ProcessingState>);

  @override
  bool get isPlaying => (super.noSuchMethod(
        Invocation.getter(#isPlaying),
        returnValue: false,
      ) as bool);

  @override
  int get queueLength => (super.noSuchMethod(
        Invocation.getter(#queueLength),
        returnValue: 0,
      ) as int);

  @override
  Map<String, dynamic> get queueStatus => (super.noSuchMethod(
        Invocation.getter(#queueStatus),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i10.Future<void> playAudio(String? audioPath) => (super.noSuchMethod(
        Invocation.method(
          #playAudio,
          [audioPath],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> stopAudio({bool? clearQueue = true}) => (super.noSuchMethod(
        Invocation.method(
          #stopAudio,
          [],
          {#clearQueue: clearQueue},
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  void forceStopState() => super.noSuchMethod(
        Invocation.method(
          #forceStopState,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<void> skipCurrent() => (super.noSuchMethod(
        Invocation.method(
          #skipCurrent,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  void clearQueue() => super.noSuchMethod(
        Invocation.method(
          #clearQueue,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setVolume(double? volume) => (super.noSuchMethod(
        Invocation.method(
          #setVolume,
          [volume],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> playAudioBytes(
    _i17.Uint8List? audioBytes, {
    String? debugName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #playAudioBytes,
          [audioBytes],
          {#debugName: debugName},
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}
