// lib/di/interfaces/i_config_service.dart
abstract class IConfigService {
  String get environment;
  bool get isProduction;
  bool get isDevelopment;
  bool get isDebug;
  String get apiBaseUrl;
  String get websocketUrl;
  Duration get apiTimeout;
  int get maxRetries;
  String? get googleClientId;
  String? get firebaseApiKey;
  String? get firebaseProjectId;
  String? get openAiApiKey;
  String? get groqApiKey;
  String? get stripePublishableKey;
  bool get enableVoiceRecording;
  bool get enableOfflineMode;
  bool get enableAnalytics;
  bool get enableCrashReporting;
  bool get enableRNNoise;
  int get audioSampleRate;
  String get audioFormat;
  int get maxRecordingDuration;
  int get sessionTimeoutMinutes;
  int get maxConcurrentSessions;
  String get databaseName;
  int get databaseVersion;
  bool get enableDatabaseLogging;
  String get logLevel;
  bool get enableFileLogging;
  String? get loggingEndpoint;
  Duration get cacheTimeout;
  int get maxCacheSize;
  bool validateConfiguration();
  List<String> getMissingRequiredConfig();
  Future<void> refreshConfiguration();
  Future<void> updateConfiguration(String key, dynamic value);
  Future<void> initialize();
  bool get isInitialized;
}
