// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // Only include Android platform since we're targeting Google Play Store
    if (defaultTargetPlatform == TargetPlatform.android) {
      return android;
    }
    
    throw UnsupportedError(
      'DefaultFirebaseOptions have not been configured for platform ${defaultTargetPlatform.name}',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '***REMOVED***',
    appId: '1:385290373302:android:01e06b856f7be445d07e17',
    messagingSenderId: '385290373302',
    projectId: 'upliftapp-cd86e',
    storageBucket: 'upliftapp-cd86e.firebasestorage.app',
  );
} 