// Mocks generated by Mockito 5.4.5 from annotations
// in ai_therapist_app/test/therapy_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:ai_therapist_app/data/datasources/remote/api_client.dart'
    as _i3;
import 'package:ai_therapist_app/services/memory_service.dart' as _i6;
import 'package:ai_therapist_app/services/therapy_graph_service.dart' as _i8;
import 'package:ai_therapist_app/services/voice_service.dart' as _i7;
import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i3.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i2.Client get httpClient =>
      (super.noSuchMethod(
            Invocation.getter(#httpClient),
            returnValue: _FakeClient_0(this, Invocation.getter(#httpClient)),
          )
          as _i2.Client);

  @override
  _i5.Future<dynamic> get(
    String? endpoint, {
    Map<String, dynamic>? queryParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#get, [endpoint], {#queryParams: queryParams}),
            returnValue: _i5.Future<dynamic>.value(),
          )
          as _i5.Future<dynamic>);

  @override
  _i5.Future<dynamic> post(String? endpoint, {dynamic body}) =>
      (super.noSuchMethod(
            Invocation.method(#post, [endpoint], {#body: body}),
            returnValue: _i5.Future<dynamic>.value(),
          )
          as _i5.Future<dynamic>);

  @override
  _i5.Future<dynamic> put(String? endpoint, {dynamic body}) =>
      (super.noSuchMethod(
            Invocation.method(#put, [endpoint], {#body: body}),
            returnValue: _i5.Future<dynamic>.value(),
          )
          as _i5.Future<dynamic>);

  @override
  _i5.Future<dynamic> patch(String? endpoint, {dynamic body}) =>
      (super.noSuchMethod(
            Invocation.method(#patch, [endpoint], {#body: body}),
            returnValue: _i5.Future<dynamic>.value(),
          )
          as _i5.Future<dynamic>);

  @override
  _i5.Future<dynamic> delete(String? endpoint) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [endpoint]),
            returnValue: _i5.Future<dynamic>.value(),
          )
          as _i5.Future<dynamic>);
}

/// A class which mocks [MemoryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMemoryService extends _i1.Mock implements _i6.MemoryService {
  MockMemoryService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> addInteraction(
    String? userMessage,
    String? aiResponse,
    Map<String, dynamic>? metadata,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addInteraction, [
              userMessage,
              aiResponse,
              metadata,
            ]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> addInsight(String? insightText, String? source) =>
      (super.noSuchMethod(
            Invocation.method(#addInsight, [insightText, source]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateEmotionalState(
    String? emotion,
    double? intensity,
    String? trigger,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateEmotionalState, [
              emotion,
              intensity,
              trigger,
            ]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateTherapeuticGoals(List<String>? goals) =>
      (super.noSuchMethod(
            Invocation.method(#updateTherapeuticGoals, [goals]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateUserPreference(String? key, dynamic value) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserPreference, [key, value]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String> getMemoryContext() =>
      (super.noSuchMethod(
            Invocation.method(#getMemoryContext, []),
            returnValue: _i5.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#getMemoryContext, []),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  int min(int? a, int? b) =>
      (super.noSuchMethod(Invocation.method(#min, [a, b]), returnValue: 0)
          as int);

  @override
  _i5.Future<void> clearAllMemory() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllMemory, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [VoiceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockVoiceService extends _i1.Mock implements _i7.VoiceService {
  MockVoiceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i7.RecordingState> get recordingState =>
      (super.noSuchMethod(
            Invocation.getter(#recordingState),
            returnValue: _i5.Stream<_i7.RecordingState>.empty(),
          )
          as _i5.Stream<_i7.RecordingState>);

  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> startRecording() =>
      (super.noSuchMethod(
            Invocation.method(#startRecording, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String> stopRecording() =>
      (super.noSuchMethod(
            Invocation.method(#stopRecording, []),
            returnValue: _i5.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#stopRecording, []),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<String> generateAudio(String? text, {bool? isAiSpeaking = true}) =>
      (super.noSuchMethod(
            Invocation.method(
              #generateAudio,
              [text],
              {#isAiSpeaking: isAiSpeaking},
            ),
            returnValue: _i5.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(
                  #generateAudio,
                  [text],
                  {#isAiSpeaking: isAiSpeaking},
                ),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<void> playAudio(String? audioPath) =>
      (super.noSuchMethod(
            Invocation.method(#playAudio, [audioPath]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TherapyGraphService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTherapyGraphService extends _i1.Mock
    implements _i8.TherapyGraphService {
  MockTherapyGraphService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<Map<String, dynamic>> get conversationStream =>
      (super.noSuchMethod(
            Invocation.getter(#conversationStream),
            returnValue: _i5.Stream<Map<String, dynamic>>.empty(),
          )
          as _i5.Stream<Map<String, dynamic>>);

  @override
  void startSession({Map<String, dynamic>? initialState}) => super.noSuchMethod(
    Invocation.method(#startSession, [], {#initialState: initialState}),
    returnValueForMissingStub: null,
  );

  @override
  void updateState(Map<String, dynamic>? updates) => super.noSuchMethod(
    Invocation.method(#updateState, [updates]),
    returnValueForMissingStub: null,
  );

  @override
  String getTherapyPrompt() =>
      (super.noSuchMethod(
            Invocation.method(#getTherapyPrompt, []),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#getTherapyPrompt, []),
            ),
          )
          as String);

  @override
  List<String> getCurrentTechniques() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentTechniques, []),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  String getTherapeuticApproach() =>
      (super.noSuchMethod(
            Invocation.method(#getTherapeuticApproach, []),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#getTherapeuticApproach, []),
            ),
          )
          as String);

  @override
  List<String> generateInterventions() =>
      (super.noSuchMethod(
            Invocation.method(#generateInterventions, []),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
