// Mocks generated by Mockito 5.4.6 from annotations
// in ai_therapist_app/test/therapy_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:ai_therapist_app/data/datasources/remote/api_client.dart'
    as _i4;
import 'package:ai_therapist_app/models/conversation_memory.dart' as _i7;
import 'package:ai_therapist_app/services/config_service.dart' as _i3;
import 'package:ai_therapist_app/services/memory_service.dart' as _i6;
import 'package:ai_therapist_app/services/therapy_graph_service.dart' as _i10;
import 'package:ai_therapist_app/services/voice_service.dart' as _i9;
import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConfigService_1 extends _i1.SmartFake implements _i3.ConfigService {
  _FakeConfigService_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i4.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get httpClient => (super.noSuchMethod(
        Invocation.getter(#httpClient),
        returnValue: _FakeClient_0(
          this,
          Invocation.getter(#httpClient),
        ),
      ) as _i2.Client);

  @override
  _i3.ConfigService get configService => (super.noSuchMethod(
        Invocation.getter(#configService),
        returnValue: _FakeConfigService_1(
          this,
          Invocation.getter(#configService),
        ),
      ) as _i3.ConfigService);

  @override
  _i5.Future<void> updateAuthToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #updateAuthToken,
          [token],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<dynamic> get(
    String? endpoint, {
    Map<String, dynamic>? queryParams,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [endpoint],
          {#queryParams: queryParams},
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);

  @override
  _i5.Future<Map<String, dynamic>> post(
    String? endpoint, {
    Map<String, dynamic>? body,
    String? contentType = 'application/json',
    bool? isFormData = false,
    Map<String, String>? additionalHeaders,
    Map<String, String>? queryParams,
    bool? forceAuth = false,
    bool? handleErrors = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [endpoint],
          {
            #body: body,
            #contentType: contentType,
            #isFormData: isFormData,
            #additionalHeaders: additionalHeaders,
            #queryParams: queryParams,
            #forceAuth: forceAuth,
            #handleErrors: handleErrors,
          },
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<dynamic> put(
    String? endpoint, {
    dynamic body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [endpoint],
          {#body: body},
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);

  @override
  _i5.Future<dynamic> patch(
    String? endpoint, {
    dynamic body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [endpoint],
          {#body: body},
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);

  @override
  _i5.Future<dynamic> delete(String? endpoint) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [endpoint],
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [MemoryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMemoryService extends _i1.Mock implements _i6.MemoryService {
  MockMemoryService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> initializeIfNeeded() => (super.noSuchMethod(
        Invocation.method(
          #initializeIfNeeded,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addMemory(
    String? userMessage,
    String? aiResponse, {
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addMemory,
          [
            userMessage,
            aiResponse,
          ],
          {#metadata: metadata},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addInsight(
    String? insight,
    String? source,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addInsight,
          [
            insight,
            source,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> recordEmotionalState(
    String? emotion,
    double? intensity, {
    String? trigger,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #recordEmotionalState,
          [
            emotion,
            intensity,
          ],
          {#trigger: trigger},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i7.ConversationMemory>> getRecentMemories(
          {int? limit = 5}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentMemories,
          [],
          {#limit: limit},
        ),
        returnValue: _i5.Future<List<_i7.ConversationMemory>>.value(
            <_i7.ConversationMemory>[]),
      ) as _i5.Future<List<_i7.ConversationMemory>>);

  @override
  _i5.Future<String> getCurrentContext({int? memoryLimit = 5}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentContext,
          [],
          {#memoryLimit: memoryLimit},
        ),
        returnValue: _i5.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #getCurrentContext,
            [],
            {#memoryLimit: memoryLimit},
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> clearMemory() => (super.noSuchMethod(
        Invocation.method(
          #clearMemory,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  int min(
    int? a,
    int? b,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #min,
          [
            a,
            b,
          ],
        ),
        returnValue: 0,
      ) as int);
}

/// A class which mocks [VoiceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockVoiceService extends _i1.Mock implements _i9.VoiceService {
  MockVoiceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i9.RecordingState> get recordingState => (super.noSuchMethod(
        Invocation.getter(#recordingState),
        returnValue: _i5.Stream<_i9.RecordingState>.empty(),
      ) as _i5.Stream<_i9.RecordingState>);

  @override
  String get apiUrl => (super.noSuchMethod(
        Invocation.getter(#apiUrl),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#apiUrl),
        ),
      ) as String);

  @override
  _i5.Stream<bool> get audioPlaybackStream => (super.noSuchMethod(
        Invocation.getter(#audioPlaybackStream),
        returnValue: _i5.Stream<bool>.empty(),
      ) as _i5.Stream<bool>);

  @override
  _i5.Stream<bool> get isTtsActuallySpeaking => (super.noSuchMethod(
        Invocation.getter(#isTtsActuallySpeaking),
        returnValue: _i5.Stream<bool>.empty(),
      ) as _i5.Stream<bool>);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> initializeOnlyIfNeeded() => (super.noSuchMethod(
        Invocation.method(
          #initializeOnlyIfNeeded,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> startRecording() => (super.noSuchMethod(
        Invocation.method(
          #startRecording,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String> stopRecording() => (super.noSuchMethod(
        Invocation.method(
          #stopRecording,
          [],
        ),
        returnValue: _i5.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #stopRecording,
            [],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> generateAudio(
    String? text, {
    bool? isAiSpeaking = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateAudio,
          [text],
          {#isAiSpeaking: isAiSpeaking},
        ),
        returnValue: _i5.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #generateAudio,
            [text],
            {#isAiSpeaking: isAiSpeaking},
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> playAudio(String? audioPath) => (super.noSuchMethod(
        Invocation.method(
          #playAudio,
          [audioPath],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> stopAudio() => (super.noSuchMethod(
        Invocation.method(
          #stopAudio,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> playStreamingAudio(String? audioUrl) => (super.noSuchMethod(
        Invocation.method(
          #playStreamingAudio,
          [audioUrl],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> isPlaying() => (super.noSuchMethod(
        Invocation.method(
          #isPlaying,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> speakWithTts(String? text) => (super.noSuchMethod(
        Invocation.method(
          #speakWithTts,
          [text],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [TherapyGraphService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTherapyGraphService extends _i1.Mock
    implements _i10.TherapyGraphService {
  MockTherapyGraphService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<Map<String, dynamic>> get conversationStream =>
      (super.noSuchMethod(
        Invocation.getter(#conversationStream),
        returnValue: _i5.Stream<Map<String, dynamic>>.empty(),
      ) as _i5.Stream<Map<String, dynamic>>);

  @override
  void startSession({Map<String, dynamic>? initialState}) => super.noSuchMethod(
        Invocation.method(
          #startSession,
          [],
          {#initialState: initialState},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateState(Map<String, dynamic>? updates) => super.noSuchMethod(
        Invocation.method(
          #updateState,
          [updates],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String getTherapyPrompt() => (super.noSuchMethod(
        Invocation.method(
          #getTherapyPrompt,
          [],
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #getTherapyPrompt,
            [],
          ),
        ),
      ) as String);

  @override
  List<String> getCurrentTechniques() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentTechniques,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  String getTherapeuticApproach() => (super.noSuchMethod(
        Invocation.method(
          #getTherapeuticApproach,
          [],
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #getTherapeuticApproach,
            [],
          ),
        ),
      ) as String);

  @override
  List<String> generateInterventions() => (super.noSuchMethod(
        Invocation.method(
          #generateInterventions,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
