// Mocks generated by Mockito 5.4.6 from annotations
// in ai_therapist_app/test/therapy_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:typed_data' as _i10;

import 'package:ai_therapist_app/data/datasources/remote/api_client.dart'
    as _i7;
import 'package:ai_therapist_app/models/conversation_memory.dart' as _i12;
import 'package:ai_therapist_app/services/audio_player_manager.dart' as _i5;
import 'package:ai_therapist_app/services/auto_listening_coordinator.dart'
    as _i4;
import 'package:ai_therapist_app/services/base_voice_service.dart' as _i14;
import 'package:ai_therapist_app/services/config_service.dart' as _i3;
import 'package:ai_therapist_app/services/memory_service.dart' as _i11;
import 'package:ai_therapist_app/services/recording_manager.dart' as _i6;
import 'package:ai_therapist_app/services/therapy_graph_service.dart' as _i15;
import 'package:ai_therapist_app/services/voice_service.dart' as _i13;
import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConfigService_1 extends _i1.SmartFake implements _i3.ConfigService {
  _FakeConfigService_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAutoListeningCoordinator_2 extends _i1.SmartFake
    implements _i4.AutoListeningCoordinator {
  _FakeAutoListeningCoordinator_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAudioPlayerManager_3 extends _i1.SmartFake
    implements _i5.AudioPlayerManager {
  _FakeAudioPlayerManager_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRecordingManager_4 extends _i1.SmartFake
    implements _i6.RecordingManager {
  _FakeRecordingManager_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i7.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get httpClient => (super.noSuchMethod(
        Invocation.getter(#httpClient),
        returnValue: _FakeClient_0(
          this,
          Invocation.getter(#httpClient),
        ),
      ) as _i2.Client);

  @override
  _i3.ConfigService get configService => (super.noSuchMethod(
        Invocation.getter(#configService),
        returnValue: _FakeConfigService_1(
          this,
          Invocation.getter(#configService),
        ),
      ) as _i3.ConfigService);

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  bool get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: false,
      ) as bool);

  @override
  _i9.Stream<String> get errorStream => (super.noSuchMethod(
        Invocation.getter(#errorStream),
        returnValue: _i9.Stream<String>.empty(),
      ) as _i9.Stream<String>);

  @override
  _i9.Future<void> updateAuthToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #updateAuthToken,
          [token],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<Map<String, dynamic>> get(
    String? endpoint, {
    Map<String, String>? headers,
    Map<String, dynamic>? queryParams,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [endpoint],
          {
            #headers: headers,
            #queryParams: queryParams,
          },
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> post(
    String? endpoint,
    Map<String, dynamic>? data, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [
            endpoint,
            data,
          ],
          {#headers: headers},
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> put(
    String? endpoint,
    Map<String, dynamic>? data, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [
            endpoint,
            data,
          ],
          {#headers: headers},
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<dynamic> patch(
    String? endpoint, {
    dynamic body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [endpoint],
          {#body: body},
        ),
        returnValue: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);

  @override
  _i9.Future<Map<String, dynamic>> delete(
    String? endpoint, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [endpoint],
          {#headers: headers},
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> uploadFile(
    String? endpoint,
    String? fieldName,
    _i10.Uint8List? fileData,
    String? fileName, {
    Map<String, String>? headers,
    Map<String, String>? additionalFields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadFile,
          [
            endpoint,
            fieldName,
            fileData,
            fileName,
          ],
          {
            #headers: headers,
            #additionalFields: additionalFields,
          },
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<_i10.Uint8List> downloadFile(String? url) => (super.noSuchMethod(
        Invocation.method(
          #downloadFile,
          [url],
        ),
        returnValue: _i9.Future<_i10.Uint8List>.value(_i10.Uint8List(0)),
      ) as _i9.Future<_i10.Uint8List>);

  @override
  void setAuthToken(String? token) => super.noSuchMethod(
        Invocation.method(
          #setAuthToken,
          [token],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearAuthToken() => super.noSuchMethod(
        Invocation.method(
          #clearAuthToken,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setBaseUrl(String? url) => super.noSuchMethod(
        Invocation.method(
          #setBaseUrl,
          [url],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setTimeout(Duration? timeout) => super.noSuchMethod(
        Invocation.method(
          #setTimeout,
          [timeout],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<bool> checkConnection() => (super.noSuchMethod(
        Invocation.method(
          #checkConnection,
          [],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<Map<String, dynamic>> callLLMDirect(
    String? systemPrompt,
    String? userMessage, {
    List<Map<String, String>>? conversationHistory,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #callLLMDirect,
          [
            systemPrompt,
            userMessage,
          ],
          {
            #conversationHistory: conversationHistory,
            #additionalParams: additionalParams,
          },
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);
}

/// A class which mocks [MemoryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMemoryService extends _i1.Mock implements _i11.MemoryService {
  MockMemoryService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i9.Future<void> initializeIfNeeded() => (super.noSuchMethod(
        Invocation.method(
          #initializeIfNeeded,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> addMemory(
    String? userMessage,
    String? aiResponse, {
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addMemory,
          [
            userMessage,
            aiResponse,
          ],
          {#metadata: metadata},
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> addInsight(
    String? insight,
    String? source,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addInsight,
          [
            insight,
            source,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> recordEmotionalState(
    String? emotion,
    double? intensity, {
    String? trigger,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #recordEmotionalState,
          [
            emotion,
            intensity,
          ],
          {#trigger: trigger},
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<List<_i12.ConversationMemory>> getRecentMemories(
          {int? limit = 5}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentMemories,
          [],
          {#limit: limit},
        ),
        returnValue: _i9.Future<List<_i12.ConversationMemory>>.value(
            <_i12.ConversationMemory>[]),
      ) as _i9.Future<List<_i12.ConversationMemory>>);

  @override
  _i9.Future<String> getCurrentContext({int? memoryLimit = 5}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentContext,
          [],
          {#memoryLimit: memoryLimit},
        ),
        returnValue: _i9.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #getCurrentContext,
            [],
            {#memoryLimit: memoryLimit},
          ),
        )),
      ) as _i9.Future<String>);

  @override
  _i9.Future<void> clearMemory() => (super.noSuchMethod(
        Invocation.method(
          #clearMemory,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  int min(
    int? a,
    int? b,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #min,
          [
            a,
            b,
          ],
        ),
        returnValue: 0,
      ) as int);
}

/// A class which mocks [VoiceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockVoiceService extends _i1.Mock implements _i13.VoiceService {
  MockVoiceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAiSpeaking => (super.noSuchMethod(
        Invocation.getter(#isAiSpeaking),
        returnValue: false,
      ) as bool);

  @override
  _i9.Stream<_i14.RecordingState> get recordingState => (super.noSuchMethod(
        Invocation.getter(#recordingState),
        returnValue: _i9.Stream<_i14.RecordingState>.empty(),
      ) as _i9.Stream<_i14.RecordingState>);

  @override
  String get apiUrl => (super.noSuchMethod(
        Invocation.getter(#apiUrl),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#apiUrl),
        ),
      ) as String);

  @override
  _i9.Stream<bool> get audioPlaybackStream => (super.noSuchMethod(
        Invocation.getter(#audioPlaybackStream),
        returnValue: _i9.Stream<bool>.empty(),
      ) as _i9.Stream<bool>);

  @override
  _i9.Stream<bool> get isTtsActuallySpeaking => (super.noSuchMethod(
        Invocation.getter(#isTtsActuallySpeaking),
        returnValue: _i9.Stream<bool>.empty(),
      ) as _i9.Stream<bool>);

  @override
  _i9.Stream<_i4.AutoListeningState> get autoListeningStateStream =>
      (super.noSuchMethod(
        Invocation.getter(#autoListeningStateStream),
        returnValue: _i9.Stream<_i4.AutoListeningState>.empty(),
      ) as _i9.Stream<_i4.AutoListeningState>);

  @override
  _i9.Stream<bool> get autoListeningModeEnabledStream => (super.noSuchMethod(
        Invocation.getter(#autoListeningModeEnabledStream),
        returnValue: _i9.Stream<bool>.empty(),
      ) as _i9.Stream<bool>);

  @override
  _i4.AutoListeningCoordinator get autoListeningCoordinator =>
      (super.noSuchMethod(
        Invocation.getter(#autoListeningCoordinator),
        returnValue: _FakeAutoListeningCoordinator_2(
          this,
          Invocation.getter(#autoListeningCoordinator),
        ),
      ) as _i4.AutoListeningCoordinator);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  set isAiSpeaking(bool? _isAiSpeaking) => super.noSuchMethod(
        Invocation.setter(
          #isAiSpeaking,
          _isAiSpeaking,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<void> enableAutoMode() => (super.noSuchMethod(
        Invocation.method(
          #enableAutoMode,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> disableAutoMode() => (super.noSuchMethod(
        Invocation.method(
          #disableAutoMode,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> enableAutoModeWithAudioState(bool? isAudioPlaying) =>
      (super.noSuchMethod(
        Invocation.method(
          #enableAutoModeWithAudioState,
          [isAudioPlaying],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> initializeOnlyIfNeeded() => (super.noSuchMethod(
        Invocation.method(
          #initializeOnlyIfNeeded,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> startRecording() => (super.noSuchMethod(
        Invocation.method(
          #startRecording,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<String?> stopRecording() => (super.noSuchMethod(
        Invocation.method(
          #stopRecording,
          [],
        ),
        returnValue: _i9.Future<String?>.value(),
      ) as _i9.Future<String?>);

  @override
  _i9.Future<String> processRecordedAudioFile(String? recordedFilePath) =>
      (super.noSuchMethod(
        Invocation.method(
          #processRecordedAudioFile,
          [recordedFilePath],
        ),
        returnValue: _i9.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #processRecordedAudioFile,
            [recordedFilePath],
          ),
        )),
      ) as _i9.Future<String>);

  @override
  _i9.Future<void> playAudio(String? audioPath) => (super.noSuchMethod(
        Invocation.method(
          #playAudio,
          [audioPath],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> stopAudio() => (super.noSuchMethod(
        Invocation.method(
          #stopAudio,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> playStreamingAudio(String? audioUrl) => (super.noSuchMethod(
        Invocation.method(
          #playStreamingAudio,
          [audioUrl],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<bool> isPlaying() => (super.noSuchMethod(
        Invocation.method(
          #isPlaying,
          [],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.AudioPlayerManager getAudioPlayerManager() => (super.noSuchMethod(
        Invocation.method(
          #getAudioPlayerManager,
          [],
        ),
        returnValue: _FakeAudioPlayerManager_3(
          this,
          Invocation.method(
            #getAudioPlayerManager,
            [],
          ),
        ),
      ) as _i5.AudioPlayerManager);

  @override
  _i6.RecordingManager getRecordingManager() => (super.noSuchMethod(
        Invocation.method(
          #getRecordingManager,
          [],
        ),
        returnValue: _FakeRecordingManager_4(
          this,
          Invocation.method(
            #getRecordingManager,
            [],
          ),
        ),
      ) as _i6.RecordingManager);

  @override
  _i9.Future<void> playAudioWithCallbacks(
    String? filePath, {
    void Function()? onDone,
    void Function(String)? onError,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #playAudioWithCallbacks,
          [filePath],
          {
            #onDone: onDone,
            #onError: onError,
          },
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  void updateTTSSpeakingState(bool? isSpeaking, {int? playbackToken}) =>
      super.noSuchMethod(
        Invocation.method(
          #updateTTSSpeakingState,
          [isSpeaking],
          {#playbackToken: playbackToken},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<void> pauseVAD() => (super.noSuchMethod(
        Invocation.method(
          #pauseVAD,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> resumeVAD() => (super.noSuchMethod(
        Invocation.method(
          #resumeVAD,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  void resetTTSState() => super.noSuchMethod(
        Invocation.method(
          #resetTTSState,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<void> setSpeakerMuted(bool? muted) => (super.noSuchMethod(
        Invocation.method(
          #setSpeakerMuted,
          [muted],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}

/// A class which mocks [TherapyGraphService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTherapyGraphService extends _i1.Mock
    implements _i15.TherapyGraphService {
  MockTherapyGraphService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Stream<Map<String, dynamic>> get conversationStream =>
      (super.noSuchMethod(
        Invocation.getter(#conversationStream),
        returnValue: _i9.Stream<Map<String, dynamic>>.empty(),
      ) as _i9.Stream<Map<String, dynamic>>);

  @override
  void startSession({Map<String, dynamic>? initialState}) => super.noSuchMethod(
        Invocation.method(
          #startSession,
          [],
          {#initialState: initialState},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateState(Map<String, dynamic>? updates) => super.noSuchMethod(
        Invocation.method(
          #updateState,
          [updates],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String getTherapyPrompt() => (super.noSuchMethod(
        Invocation.method(
          #getTherapyPrompt,
          [],
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #getTherapyPrompt,
            [],
          ),
        ),
      ) as String);

  @override
  List<String> getCurrentTechniques() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentTechniques,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  String getTherapeuticApproach() => (super.noSuchMethod(
        Invocation.method(
          #getTherapeuticApproach,
          [],
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #getTherapeuticApproach,
            [],
          ),
        ),
      ) as String);

  @override
  List<String> generateInterventions() => (super.noSuchMethod(
        Invocation.method(
          #generateInterventions,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
