// Mocks generated by Mockito 5.4.6 from annotations
// in ai_therapist_app/test/services/auto_listening_coordinator_guard_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i6;

import 'package:ai_therapist_app/services/audio_player_manager.dart' as _i3;
import 'package:ai_therapist_app/services/auto_listening_coordinator.dart'
    as _i11;
import 'package:ai_therapist_app/services/base_voice_service.dart' as _i7;
import 'package:ai_therapist_app/services/enhanced_vad_manager.dart' as _i14;
import 'package:ai_therapist_app/services/gemini_live_duplex_controller.dart'
    as _i12;
import 'package:ai_therapist_app/services/pipeline/voice_pipeline_controller.dart'
    as _i13;
import 'package:ai_therapist_app/services/recording_manager.dart' as _i4;
import 'package:ai_therapist_app/services/voice_service.dart' as _i9;
import 'package:just_audio/just_audio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:record/record.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAudioPlayer_0 extends _i1.SmartFake implements _i2.AudioPlayer {
  _FakeAudioPlayer_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDuration_1 extends _i1.SmartFake implements Duration {
  _FakeDuration_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAudioPlayerManager_2 extends _i1.SmartFake
    implements _i3.AudioPlayerManager {
  _FakeAudioPlayerManager_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRecordingManager_3 extends _i1.SmartFake
    implements _i4.RecordingManager {
  _FakeRecordingManager_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AudioPlayerManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioPlayerManager extends _i1.Mock
    implements _i3.AudioPlayerManager {
  MockAudioPlayerManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<bool> get isPlayingStream => (super.noSuchMethod(
        Invocation.getter(#isPlayingStream),
        returnValue: _i5.Stream<bool>.empty(),
      ) as _i5.Stream<bool>);

  @override
  _i5.Stream<String?> get errorStream => (super.noSuchMethod(
        Invocation.getter(#errorStream),
        returnValue: _i5.Stream<String?>.empty(),
      ) as _i5.Stream<String?>);

  @override
  _i5.Stream<int> get queueLengthStream => (super.noSuchMethod(
        Invocation.getter(#queueLengthStream),
        returnValue: _i5.Stream<int>.empty(),
      ) as _i5.Stream<int>);

  @override
  _i5.Stream<String?> get nowPlayingStream => (super.noSuchMethod(
        Invocation.getter(#nowPlayingStream),
        returnValue: _i5.Stream<String?>.empty(),
      ) as _i5.Stream<String?>);

  @override
  _i5.Stream<bool> get muteStateStream => (super.noSuchMethod(
        Invocation.getter(#muteStateStream),
        returnValue: _i5.Stream<bool>.empty(),
      ) as _i5.Stream<bool>);

  @override
  _i5.Stream<bool> get playbackActiveStream => (super.noSuchMethod(
        Invocation.getter(#playbackActiveStream),
        returnValue: _i5.Stream<bool>.empty(),
      ) as _i5.Stream<bool>);

  @override
  _i5.Stream<_i2.ProcessingState> get processingStateStream =>
      (super.noSuchMethod(
        Invocation.getter(#processingStateStream),
        returnValue: _i5.Stream<_i2.ProcessingState>.empty(),
      ) as _i5.Stream<_i2.ProcessingState>);

  @override
  bool get isPlaying => (super.noSuchMethod(
        Invocation.getter(#isPlaying),
        returnValue: false,
      ) as bool);

  @override
  bool get isPlaybackActive => (super.noSuchMethod(
        Invocation.getter(#isPlaybackActive),
        returnValue: false,
      ) as bool);

  @override
  _i2.AudioPlayer get audioPlayer => (super.noSuchMethod(
        Invocation.getter(#audioPlayer),
        returnValue: _FakeAudioPlayer_0(
          this,
          Invocation.getter(#audioPlayer),
        ),
      ) as _i2.AudioPlayer);

  @override
  int get queueLength => (super.noSuchMethod(
        Invocation.getter(#queueLength),
        returnValue: 0,
      ) as int);

  @override
  Map<String, dynamic> get queueStatus => (super.noSuchMethod(
        Invocation.getter(#queueStatus),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  bool get isSoftMuted => (super.noSuchMethod(
        Invocation.getter(#isSoftMuted),
        returnValue: false,
      ) as bool);

  @override
  bool get disposed => (super.noSuchMethod(
        Invocation.getter(#disposed),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> get disposalComplete => (super.noSuchMethod(
        Invocation.getter(#disposalComplete),
        returnValue: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  bool get canOperate => (super.noSuchMethod(
        Invocation.getter(#canOperate),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> playAudio(String? audioPath) => (super.noSuchMethod(
        Invocation.method(
          #playAudio,
          [audioPath],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> stopAudio({bool? clearQueue = true}) => (super.noSuchMethod(
        Invocation.method(
          #stopAudio,
          [],
          {#clearQueue: clearQueue},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> lightweightReset() => (super.noSuchMethod(
        Invocation.method(
          #lightweightReset,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void forceStopState() => super.noSuchMethod(
        Invocation.method(
          #forceStopState,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> skipCurrent() => (super.noSuchMethod(
        Invocation.method(
          #skipCurrent,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void clearQueue() => super.noSuchMethod(
        Invocation.method(
          #clearQueue,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> sessionEndCleanup() => (super.noSuchMethod(
        Invocation.method(
          #sessionEndCleanup,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> performAsyncDisposal() => (super.noSuchMethod(
        Invocation.method(
          #performAsyncDisposal,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void performDisposal() => super.noSuchMethod(
        Invocation.method(
          #performDisposal,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> setVolume(double? volume) => (super.noSuchMethod(
        Invocation.method(
          #setVolume,
          [volume],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void mute(bool? muted) => super.noSuchMethod(
        Invocation.method(
          #mute,
          [muted],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> playLiveTtsStream(
    dynamic audioSourceOrStream, {
    String? debugName,
    String? contentType = 'audio/wav',
    void Function(int)? onPlaybackToken,
    void Function(int)? onNaturalCompletion,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #playLiveTtsStream,
          [audioSourceOrStream],
          {
            #debugName: debugName,
            #contentType: contentType,
            #onPlaybackToken: onPlaybackToken,
            #onNaturalCompletion: onNaturalCompletion,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> playAudioBytes(
    _i6.Uint8List? audioBytes, {
    String? debugName,
    String? mimeType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #playAudioBytes,
          [audioBytes],
          {
            #debugName: debugName,
            #mimeType: mimeType,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> disposeAsync() => (super.noSuchMethod(
        Invocation.method(
          #disposeAsync,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void checkNotDisposed([String? operation]) => super.noSuchMethod(
        Invocation.method(
          #checkNotDisposed,
          [operation],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [RecordingManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecordingManager extends _i1.Mock implements _i4.RecordingManager {
  MockRecordingManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i7.RecordingState> get recordingStateStream =>
      (super.noSuchMethod(
        Invocation.getter(#recordingStateStream),
        returnValue: _i5.Stream<_i7.RecordingState>.empty(),
      ) as _i5.Stream<_i7.RecordingState>);

  @override
  _i5.Stream<String?> get errorStream => (super.noSuchMethod(
        Invocation.getter(#errorStream),
        returnValue: _i5.Stream<String?>.empty(),
      ) as _i5.Stream<String?>);

  @override
  _i7.RecordingState get currentState => (super.noSuchMethod(
        Invocation.getter(#currentState),
        returnValue: _i7.RecordingState.stopped,
      ) as _i7.RecordingState);

  @override
  bool get isStreaming => (super.noSuchMethod(
        Invocation.getter(#isStreaming),
        returnValue: false,
      ) as bool);

  @override
  Duration get elapsed => (super.noSuchMethod(
        Invocation.getter(#elapsed),
        returnValue: _FakeDuration_1(
          this,
          Invocation.getter(#elapsed),
        ),
      ) as Duration);

  @override
  Set<String> get pendingTranscriptionPaths => (super.noSuchMethod(
        Invocation.getter(#pendingTranscriptionPaths),
        returnValue: <String>{},
      ) as Set<String>);

  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i5.Stream<_i6.Uint8List>> startStreaming({
    int? sampleRate = 24000,
    int? numChannels = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startStreaming,
          [],
          {
            #sampleRate: sampleRate,
            #numChannels: numChannels,
          },
        ),
        returnValue: _i5.Future<_i5.Stream<_i6.Uint8List>>.value(
            _i5.Stream<_i6.Uint8List>.empty()),
      ) as _i5.Future<_i5.Stream<_i6.Uint8List>>);

  @override
  _i5.Future<bool> requestPermissions() => (super.noSuchMethod(
        Invocation.method(
          #requestPermissions,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> startRecording() => (super.noSuchMethod(
        Invocation.method(
          #startRecording,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> stopStreaming() => (super.noSuchMethod(
        Invocation.method(
          #stopStreaming,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String?> stopRecording() => (super.noSuchMethod(
        Invocation.method(
          #stopRecording,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<String?> tryStopRecording() => (super.noSuchMethod(
        Invocation.method(
          #tryStopRecording,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  void markFileAsPendingTranscription(String? filePath) => super.noSuchMethod(
        Invocation.method(
          #markFileAsPendingTranscription,
          [filePath],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void markTranscriptionComplete(String? filePath) => super.noSuchMethod(
        Invocation.method(
          #markTranscriptionComplete,
          [filePath],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<_i8.Amplitude?> getCurrentAmplitude() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentAmplitude,
          [],
        ),
        returnValue: _i5.Future<_i8.Amplitude?>.value(),
      ) as _i5.Future<_i8.Amplitude?>);

  @override
  _i5.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [VoiceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockVoiceService extends _i1.Mock implements _i9.VoiceService {
  MockVoiceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAiSpeaking => (super.noSuchMethod(
        Invocation.getter(#isAiSpeaking),
        returnValue: false,
      ) as bool);

  @override
  _i5.Stream<_i7.RecordingState> get recordingState => (super.noSuchMethod(
        Invocation.getter(#recordingState),
        returnValue: _i5.Stream<_i7.RecordingState>.empty(),
      ) as _i5.Stream<_i7.RecordingState>);

  @override
  String get apiUrl => (super.noSuchMethod(
        Invocation.getter(#apiUrl),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#apiUrl),
        ),
      ) as String);

  @override
  _i5.Stream<bool> get audioPlaybackStream => (super.noSuchMethod(
        Invocation.getter(#audioPlaybackStream),
        returnValue: _i5.Stream<bool>.empty(),
      ) as _i5.Stream<bool>);

  @override
  _i5.Stream<bool> get isTtsActuallySpeaking => (super.noSuchMethod(
        Invocation.getter(#isTtsActuallySpeaking),
        returnValue: _i5.Stream<bool>.empty(),
      ) as _i5.Stream<bool>);

  @override
  bool get isTtsActive => (super.noSuchMethod(
        Invocation.getter(#isTtsActive),
        returnValue: false,
      ) as bool);

  @override
  bool get isRecordingActive => (super.noSuchMethod(
        Invocation.getter(#isRecordingActive),
        returnValue: false,
      ) as bool);

  @override
  _i5.Stream<_i11.AutoListeningState> get autoListeningStateStream =>
      (super.noSuchMethod(
        Invocation.getter(#autoListeningStateStream),
        returnValue: _i5.Stream<_i11.AutoListeningState>.empty(),
      ) as _i5.Stream<_i11.AutoListeningState>);

  @override
  _i5.Stream<bool> get autoListeningModeEnabledStream => (super.noSuchMethod(
        Invocation.getter(#autoListeningModeEnabledStream),
        returnValue: _i5.Stream<bool>.empty(),
      ) as _i5.Stream<bool>);

  @override
  _i11.AutoListeningState get autoListeningState => (super.noSuchMethod(
        Invocation.getter(#autoListeningState),
        returnValue: _i11.AutoListeningState.idle,
      ) as _i11.AutoListeningState);

  @override
  bool get isAutoModeEnabled => (super.noSuchMethod(
        Invocation.getter(#isAutoModeEnabled),
        returnValue: false,
      ) as bool);

  @override
  bool get geminiLiveEnabled => (super.noSuchMethod(
        Invocation.getter(#geminiLiveEnabled),
        returnValue: false,
      ) as bool);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i5.Stream<_i12.GeminiLiveEvent> get geminiLiveEventStream =>
      (super.noSuchMethod(
        Invocation.getter(#geminiLiveEventStream),
        returnValue: _i5.Stream<_i12.GeminiLiveEvent>.empty(),
      ) as _i5.Stream<_i12.GeminiLiveEvent>);

  @override
  set isAiSpeaking(bool? _isAiSpeaking) => super.noSuchMethod(
        Invocation.setter(
          #isAiSpeaking,
          _isAiSpeaking,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set canStartListeningCallback(bool Function()? _canStartListeningCallback) =>
      super.noSuchMethod(
        Invocation.setter(
          #canStartListeningCallback,
          _canStartListeningCallback,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set getCurrentGeneration(int Function()? _getCurrentGeneration) =>
      super.noSuchMethod(
        Invocation.setter(
          #getCurrentGeneration,
          _getCurrentGeneration,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set isVoiceModeCallback(bool Function()? callback) => super.noSuchMethod(
        Invocation.setter(
          #isVoiceModeCallback,
          callback,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> enableAutoMode() => (super.noSuchMethod(
        Invocation.method(
          #enableAutoMode,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> disableAutoMode() => (super.noSuchMethod(
        Invocation.method(
          #disableAutoMode,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> enableAutoModeWithAudioState(bool? isAudioPlaying) =>
      (super.noSuchMethod(
        Invocation.method(
          #enableAutoModeWithAudioState,
          [isAudioPlaying],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> initializeAutoListening() => (super.noSuchMethod(
        Invocation.method(
          #initializeAutoListening,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void resetAutoListening({
    bool? full = false,
    bool? preserveAutoMode,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #resetAutoListening,
          [],
          {
            #full: full,
            #preserveAutoMode: preserveAutoMode,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setAutoListeningRecordingCallback(void Function(String)? callback) =>
      super.noSuchMethod(
        Invocation.method(
          #setAutoListeningRecordingCallback,
          [callback],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setAutoListeningTtsActivityStream(_i5.Stream<bool>? stream) =>
      super.noSuchMethod(
        Invocation.method(
          #setAutoListeningTtsActivityStream,
          [stream],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void triggerListening() => super.noSuchMethod(
        Invocation.method(
          #triggerListening,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> enableAutoModeWhenPlaybackCompletes({
    required int playbackToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #enableAutoModeWhenPlaybackCompletes,
          [],
          {#playbackToken: playbackToken},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void attachPipelineController(_i13.VoicePipelineController? controller) =>
      super.noSuchMethod(
        Invocation.method(
          #attachPipelineController,
          [controller],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> initializeOnlyIfNeeded() => (super.noSuchMethod(
        Invocation.method(
          #initializeOnlyIfNeeded,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> startRecording() => (super.noSuchMethod(
        Invocation.method(
          #startRecording,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String?> stopRecording() => (super.noSuchMethod(
        Invocation.method(
          #stopRecording,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<String?> tryStopRecording() => (super.noSuchMethod(
        Invocation.method(
          #tryStopRecording,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<void> startGeminiLiveSession({String? userId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #startGeminiLiveSession,
          [],
          {#userId: userId},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> stopGeminiLiveSession() => (super.noSuchMethod(
        Invocation.method(
          #stopGeminiLiveSession,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> sendGeminiLiveText(
    String? text, {
    bool? turnComplete = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendGeminiLiveText,
          [text],
          {#turnComplete: turnComplete},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String> processRecordedAudioFile(String? recordedFilePath) =>
      (super.noSuchMethod(
        Invocation.method(
          #processRecordedAudioFile,
          [recordedFilePath],
        ),
        returnValue: _i5.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #processRecordedAudioFile,
            [recordedFilePath],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> playAudio(String? audioPath) => (super.noSuchMethod(
        Invocation.method(
          #playAudio,
          [audioPath],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> stopAudio() => (super.noSuchMethod(
        Invocation.method(
          #stopAudio,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> playStreamingAudio(String? audioUrl) => (super.noSuchMethod(
        Invocation.method(
          #playStreamingAudio,
          [audioUrl],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> isPlaying() => (super.noSuchMethod(
        Invocation.method(
          #isPlaying,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.AudioPlayerManager getAudioPlayerManager() => (super.noSuchMethod(
        Invocation.method(
          #getAudioPlayerManager,
          [],
        ),
        returnValue: _FakeAudioPlayerManager_2(
          this,
          Invocation.method(
            #getAudioPlayerManager,
            [],
          ),
        ),
      ) as _i3.AudioPlayerManager);

  @override
  _i4.RecordingManager getRecordingManager() => (super.noSuchMethod(
        Invocation.method(
          #getRecordingManager,
          [],
        ),
        returnValue: _FakeRecordingManager_3(
          this,
          Invocation.method(
            #getRecordingManager,
            [],
          ),
        ),
      ) as _i4.RecordingManager);

  @override
  _i5.Future<void> playAudioWithCallbacks(
    String? filePath, {
    void Function()? onDone,
    void Function(String)? onError,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #playAudioWithCallbacks,
          [filePath],
          {
            #onDone: onDone,
            #onError: onError,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void updateTTSSpeakingState(
    bool? isSpeaking, {
    int? playbackToken,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #updateTTSSpeakingState,
          [isSpeaking],
          {#playbackToken: playbackToken},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> pauseVAD() => (super.noSuchMethod(
        Invocation.method(
          #pauseVAD,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> resumeVAD() => (super.noSuchMethod(
        Invocation.method(
          #resumeVAD,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void resetTTSState() => super.noSuchMethod(
        Invocation.method(
          #resetTTSState,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> setSpeakerMuted(bool? muted) => (super.noSuchMethod(
        Invocation.method(
          #setSpeakerMuted,
          [muted],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [EnhancedVADManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockEnhancedVADManager extends _i1.Mock
    implements _i14.EnhancedVADManager {
  MockEnhancedVADManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<void> get onSpeechStart => (super.noSuchMethod(
        Invocation.getter(#onSpeechStart),
        returnValue: _i5.Stream<void>.empty(),
      ) as _i5.Stream<void>);

  @override
  _i5.Stream<void> get onSpeechEnd => (super.noSuchMethod(
        Invocation.getter(#onSpeechEnd),
        returnValue: _i5.Stream<void>.empty(),
      ) as _i5.Stream<void>);

  @override
  _i5.Stream<String> get onError => (super.noSuchMethod(
        Invocation.getter(#onError),
        returnValue: _i5.Stream<String>.empty(),
      ) as _i5.Stream<String>);

  @override
  _i5.Stream<double> get amplitudeStream => (super.noSuchMethod(
        Invocation.getter(#amplitudeStream),
        returnValue: _i5.Stream<double>.empty(),
      ) as _i5.Stream<double>);

  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> startListening() => (super.noSuchMethod(
        Invocation.method(
          #startListening,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> stopListening() => (super.noSuchMethod(
        Invocation.method(
          #stopListening,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void setSpeechThreshold(double? threshold) => super.noSuchMethod(
        Invocation.method(
          #setSpeechThreshold,
          [threshold],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> getConfiguration() => (super.noSuchMethod(
        Invocation.method(
          #getConfiguration,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i5.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> waitForWorkerExit() => (super.noSuchMethod(
        Invocation.method(
          #waitForWorkerExit,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
