// Mocks generated by Mockito 5.4.6 from annotations
// in ai_therapist_app/test/services/voice_service_characterization_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:convert' as _i14;
import 'dart:io' as _i4;
import 'dart:typed_data' as _i9;

import 'package:ai_therapist_app/data/datasources/remote/api_client.dart'
    as _i12;
import 'package:ai_therapist_app/services/audio_player_manager.dart' as _i7;
import 'package:ai_therapist_app/services/auto_listening_coordinator.dart'
    as _i5;
import 'package:ai_therapist_app/services/base_voice_service.dart' as _i11;
import 'package:ai_therapist_app/services/config_service.dart' as _i3;
import 'package:ai_therapist_app/services/recording_manager.dart' as _i10;
import 'package:http/http.dart' as _i2;
import 'package:just_audio/just_audio.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDuration_0 extends _i1.SmartFake implements Duration {
  _FakeDuration_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClient_1 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConfigService_2 extends _i1.SmartFake implements _i3.ConfigService {
  _FakeConfigService_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFile_3 extends _i1.SmartFake implements _i4.File {
  _FakeFile_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUri_4 extends _i1.SmartFake implements Uri {
  _FakeUri_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDirectory_5 extends _i1.SmartFake implements _i4.Directory {
  _FakeDirectory_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFileSystemEntity_6 extends _i1.SmartFake
    implements _i4.FileSystemEntity {
  _FakeFileSystemEntity_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDateTime_7 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRandomAccessFile_8 extends _i1.SmartFake
    implements _i4.RandomAccessFile {
  _FakeRandomAccessFile_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIOSink_9 extends _i1.SmartFake implements _i4.IOSink {
  _FakeIOSink_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFileStat_10 extends _i1.SmartFake implements _i4.FileStat {
  _FakeFileStat_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AutoListeningCoordinator].
///
/// See the documentation for Mockito's code generation for more information.
class MockAutoListeningCoordinator extends _i1.Mock
    implements _i5.AutoListeningCoordinator {
  MockAutoListeningCoordinator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Stream<bool> get autoModeEnabledStream => (super.noSuchMethod(
        Invocation.getter(#autoModeEnabledStream),
        returnValue: _i6.Stream<bool>.empty(),
      ) as _i6.Stream<bool>);

  @override
  _i6.Stream<_i5.AutoListeningState> get stateStream => (super.noSuchMethod(
        Invocation.getter(#stateStream),
        returnValue: _i6.Stream<_i5.AutoListeningState>.empty(),
      ) as _i6.Stream<_i5.AutoListeningState>);

  @override
  _i6.Stream<String?> get errorStream => (super.noSuchMethod(
        Invocation.getter(#errorStream),
        returnValue: _i6.Stream<String?>.empty(),
      ) as _i6.Stream<String?>);

  @override
  bool get autoModeEnabled => (super.noSuchMethod(
        Invocation.getter(#autoModeEnabled),
        returnValue: false,
      ) as bool);

  @override
  _i5.AutoListeningState get currentState => (super.noSuchMethod(
        Invocation.getter(#currentState),
        returnValue: _i5.AutoListeningState.idle,
      ) as _i5.AutoListeningState);

  @override
  set onSpeechDetectedCallback(dynamic Function()? _onSpeechDetectedCallback) =>
      super.noSuchMethod(
        Invocation.setter(
          #onSpeechDetectedCallback,
          _onSpeechDetectedCallback,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set onRecordingCompleteCallback(
          dynamic Function(String)? _onRecordingCompleteCallback) =>
      super.noSuchMethod(
        Invocation.setter(
          #onRecordingCompleteCallback,
          _onRecordingCompleteCallback,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> enableAutoModeWithAudioState(bool? isAudioPlaying) =>
      (super.noSuchMethod(
        Invocation.method(
          #enableAutoModeWithAudioState,
          [isAudioPlaying],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> enableAutoMode() => (super.noSuchMethod(
        Invocation.method(
          #enableAutoMode,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> disableAutoMode() => (super.noSuchMethod(
        Invocation.method(
          #disableAutoMode,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void triggerListening() => super.noSuchMethod(
        Invocation.method(
          #triggerListening,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onProcessingComplete() => super.noSuchMethod(
        Invocation.method(
          #onProcessingComplete,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void startListening() => super.noSuchMethod(
        Invocation.method(
          #startListening,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void stopListening() => super.noSuchMethod(
        Invocation.method(
          #stopListening,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AudioPlayerManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioPlayerManager extends _i1.Mock
    implements _i7.AudioPlayerManager {
  MockAudioPlayerManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Stream<bool> get isPlayingStream => (super.noSuchMethod(
        Invocation.getter(#isPlayingStream),
        returnValue: _i6.Stream<bool>.empty(),
      ) as _i6.Stream<bool>);

  @override
  _i6.Stream<String?> get errorStream => (super.noSuchMethod(
        Invocation.getter(#errorStream),
        returnValue: _i6.Stream<String?>.empty(),
      ) as _i6.Stream<String?>);

  @override
  _i6.Stream<int> get queueLengthStream => (super.noSuchMethod(
        Invocation.getter(#queueLengthStream),
        returnValue: _i6.Stream<int>.empty(),
      ) as _i6.Stream<int>);

  @override
  _i6.Stream<String?> get nowPlayingStream => (super.noSuchMethod(
        Invocation.getter(#nowPlayingStream),
        returnValue: _i6.Stream<String?>.empty(),
      ) as _i6.Stream<String?>);

  @override
  _i6.Stream<_i8.ProcessingState> get processingStateStream =>
      (super.noSuchMethod(
        Invocation.getter(#processingStateStream),
        returnValue: _i6.Stream<_i8.ProcessingState>.empty(),
      ) as _i6.Stream<_i8.ProcessingState>);

  @override
  bool get isPlaying => (super.noSuchMethod(
        Invocation.getter(#isPlaying),
        returnValue: false,
      ) as bool);

  @override
  int get queueLength => (super.noSuchMethod(
        Invocation.getter(#queueLength),
        returnValue: 0,
      ) as int);

  @override
  Map<String, dynamic> get queueStatus => (super.noSuchMethod(
        Invocation.getter(#queueStatus),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i6.Future<void> playAudio(String? audioPath) => (super.noSuchMethod(
        Invocation.method(
          #playAudio,
          [audioPath],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> stopAudio({bool? clearQueue = true}) => (super.noSuchMethod(
        Invocation.method(
          #stopAudio,
          [],
          {#clearQueue: clearQueue},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void forceStopState() => super.noSuchMethod(
        Invocation.method(
          #forceStopState,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> skipCurrent() => (super.noSuchMethod(
        Invocation.method(
          #skipCurrent,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void clearQueue() => super.noSuchMethod(
        Invocation.method(
          #clearQueue,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setVolume(double? volume) => (super.noSuchMethod(
        Invocation.method(
          #setVolume,
          [volume],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> playAudioBytes(
    _i9.Uint8List? audioBytes, {
    String? debugName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #playAudioBytes,
          [audioBytes],
          {#debugName: debugName},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [RecordingManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecordingManager extends _i1.Mock implements _i10.RecordingManager {
  MockRecordingManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Stream<_i11.RecordingState> get recordingStateStream =>
      (super.noSuchMethod(
        Invocation.getter(#recordingStateStream),
        returnValue: _i6.Stream<_i11.RecordingState>.empty(),
      ) as _i6.Stream<_i11.RecordingState>);

  @override
  _i6.Stream<String?> get errorStream => (super.noSuchMethod(
        Invocation.getter(#errorStream),
        returnValue: _i6.Stream<String?>.empty(),
      ) as _i6.Stream<String?>);

  @override
  _i11.RecordingState get currentState => (super.noSuchMethod(
        Invocation.getter(#currentState),
        returnValue: _i11.RecordingState.stopped,
      ) as _i11.RecordingState);

  @override
  Duration get elapsed => (super.noSuchMethod(
        Invocation.getter(#elapsed),
        returnValue: _FakeDuration_0(
          this,
          Invocation.getter(#elapsed),
        ),
      ) as Duration);

  @override
  Set<String> get pendingTranscriptionPaths => (super.noSuchMethod(
        Invocation.getter(#pendingTranscriptionPaths),
        returnValue: <String>{},
      ) as Set<String>);

  @override
  _i6.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> requestPermissions() => (super.noSuchMethod(
        Invocation.method(
          #requestPermissions,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> startRecording() => (super.noSuchMethod(
        Invocation.method(
          #startRecording,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<String?> stopRecording() => (super.noSuchMethod(
        Invocation.method(
          #stopRecording,
          [],
        ),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  void markFileAsPendingTranscription(String? filePath) => super.noSuchMethod(
        Invocation.method(
          #markFileAsPendingTranscription,
          [filePath],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void markTranscriptionComplete(String? filePath) => super.noSuchMethod(
        Invocation.method(
          #markTranscriptionComplete,
          [filePath],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i12.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get httpClient => (super.noSuchMethod(
        Invocation.getter(#httpClient),
        returnValue: _FakeClient_1(
          this,
          Invocation.getter(#httpClient),
        ),
      ) as _i2.Client);

  @override
  _i3.ConfigService get configService => (super.noSuchMethod(
        Invocation.getter(#configService),
        returnValue: _FakeConfigService_2(
          this,
          Invocation.getter(#configService),
        ),
      ) as _i3.ConfigService);

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i13.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  bool get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: false,
      ) as bool);

  @override
  _i6.Stream<String> get errorStream => (super.noSuchMethod(
        Invocation.getter(#errorStream),
        returnValue: _i6.Stream<String>.empty(),
      ) as _i6.Stream<String>);

  @override
  _i6.Future<void> updateAuthToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #updateAuthToken,
          [token],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<Map<String, dynamic>> get(
    String? endpoint, {
    Map<String, String>? headers,
    Map<String, dynamic>? queryParams,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [endpoint],
          {
            #headers: headers,
            #queryParams: queryParams,
          },
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> post(
    String? endpoint,
    Map<String, dynamic>? data, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [
            endpoint,
            data,
          ],
          {#headers: headers},
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> put(
    String? endpoint,
    Map<String, dynamic>? data, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [
            endpoint,
            data,
          ],
          {#headers: headers},
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<dynamic> patch(
    String? endpoint, {
    dynamic body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [endpoint],
          {#body: body},
        ),
        returnValue: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  _i6.Future<Map<String, dynamic>> delete(
    String? endpoint, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [endpoint],
          {#headers: headers},
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> uploadFile(
    String? endpoint,
    String? fieldName,
    _i9.Uint8List? fileData,
    String? fileName, {
    Map<String, String>? headers,
    Map<String, String>? additionalFields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadFile,
          [
            endpoint,
            fieldName,
            fileData,
            fileName,
          ],
          {
            #headers: headers,
            #additionalFields: additionalFields,
          },
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<_i9.Uint8List> downloadFile(String? url) => (super.noSuchMethod(
        Invocation.method(
          #downloadFile,
          [url],
        ),
        returnValue: _i6.Future<_i9.Uint8List>.value(_i9.Uint8List(0)),
      ) as _i6.Future<_i9.Uint8List>);

  @override
  void setAuthToken(String? token) => super.noSuchMethod(
        Invocation.method(
          #setAuthToken,
          [token],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearAuthToken() => super.noSuchMethod(
        Invocation.method(
          #clearAuthToken,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setBaseUrl(String? url) => super.noSuchMethod(
        Invocation.method(
          #setBaseUrl,
          [url],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setTimeout(Duration? timeout) => super.noSuchMethod(
        Invocation.method(
          #setTimeout,
          [timeout],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<bool> checkConnection() => (super.noSuchMethod(
        Invocation.method(
          #checkConnection,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<Map<String, dynamic>> callLLMDirect(
    String? systemPrompt,
    String? userMessage, {
    List<Map<String, String>>? conversationHistory,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #callLLMDirect,
          [
            systemPrompt,
            userMessage,
          ],
          {
            #conversationHistory: conversationHistory,
            #additionalParams: additionalParams,
          },
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);
}

/// A class which mocks [File].
///
/// See the documentation for Mockito's code generation for more information.
class MockFile extends _i1.Mock implements _i4.File {
  MockFile() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.File get absolute => (super.noSuchMethod(
        Invocation.getter(#absolute),
        returnValue: _FakeFile_3(
          this,
          Invocation.getter(#absolute),
        ),
      ) as _i4.File);

  @override
  String get path => (super.noSuchMethod(
        Invocation.getter(#path),
        returnValue: _i13.dummyValue<String>(
          this,
          Invocation.getter(#path),
        ),
      ) as String);

  @override
  Uri get uri => (super.noSuchMethod(
        Invocation.getter(#uri),
        returnValue: _FakeUri_4(
          this,
          Invocation.getter(#uri),
        ),
      ) as Uri);

  @override
  bool get isAbsolute => (super.noSuchMethod(
        Invocation.getter(#isAbsolute),
        returnValue: false,
      ) as bool);

  @override
  _i4.Directory get parent => (super.noSuchMethod(
        Invocation.getter(#parent),
        returnValue: _FakeDirectory_5(
          this,
          Invocation.getter(#parent),
        ),
      ) as _i4.Directory);

  @override
  _i6.Future<_i4.File> create({
    bool? recursive = false,
    bool? exclusive = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [],
          {
            #recursive: recursive,
            #exclusive: exclusive,
          },
        ),
        returnValue: _i6.Future<_i4.File>.value(_FakeFile_3(
          this,
          Invocation.method(
            #create,
            [],
            {
              #recursive: recursive,
              #exclusive: exclusive,
            },
          ),
        )),
      ) as _i6.Future<_i4.File>);

  @override
  void createSync({
    bool? recursive = false,
    bool? exclusive = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #createSync,
          [],
          {
            #recursive: recursive,
            #exclusive: exclusive,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<_i4.File> rename(String? newPath) => (super.noSuchMethod(
        Invocation.method(
          #rename,
          [newPath],
        ),
        returnValue: _i6.Future<_i4.File>.value(_FakeFile_3(
          this,
          Invocation.method(
            #rename,
            [newPath],
          ),
        )),
      ) as _i6.Future<_i4.File>);

  @override
  _i4.File renameSync(String? newPath) => (super.noSuchMethod(
        Invocation.method(
          #renameSync,
          [newPath],
        ),
        returnValue: _FakeFile_3(
          this,
          Invocation.method(
            #renameSync,
            [newPath],
          ),
        ),
      ) as _i4.File);

  @override
  _i6.Future<_i4.FileSystemEntity> delete({bool? recursive = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [],
          {#recursive: recursive},
        ),
        returnValue:
            _i6.Future<_i4.FileSystemEntity>.value(_FakeFileSystemEntity_6(
          this,
          Invocation.method(
            #delete,
            [],
            {#recursive: recursive},
          ),
        )),
      ) as _i6.Future<_i4.FileSystemEntity>);

  @override
  void deleteSync({bool? recursive = false}) => super.noSuchMethod(
        Invocation.method(
          #deleteSync,
          [],
          {#recursive: recursive},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<_i4.File> copy(String? newPath) => (super.noSuchMethod(
        Invocation.method(
          #copy,
          [newPath],
        ),
        returnValue: _i6.Future<_i4.File>.value(_FakeFile_3(
          this,
          Invocation.method(
            #copy,
            [newPath],
          ),
        )),
      ) as _i6.Future<_i4.File>);

  @override
  _i4.File copySync(String? newPath) => (super.noSuchMethod(
        Invocation.method(
          #copySync,
          [newPath],
        ),
        returnValue: _FakeFile_3(
          this,
          Invocation.method(
            #copySync,
            [newPath],
          ),
        ),
      ) as _i4.File);

  @override
  _i6.Future<int> length() => (super.noSuchMethod(
        Invocation.method(
          #length,
          [],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  int lengthSync() => (super.noSuchMethod(
        Invocation.method(
          #lengthSync,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  _i6.Future<DateTime> lastAccessed() => (super.noSuchMethod(
        Invocation.method(
          #lastAccessed,
          [],
        ),
        returnValue: _i6.Future<DateTime>.value(_FakeDateTime_7(
          this,
          Invocation.method(
            #lastAccessed,
            [],
          ),
        )),
      ) as _i6.Future<DateTime>);

  @override
  DateTime lastAccessedSync() => (super.noSuchMethod(
        Invocation.method(
          #lastAccessedSync,
          [],
        ),
        returnValue: _FakeDateTime_7(
          this,
          Invocation.method(
            #lastAccessedSync,
            [],
          ),
        ),
      ) as DateTime);

  @override
  _i6.Future<dynamic> setLastAccessed(DateTime? time) => (super.noSuchMethod(
        Invocation.method(
          #setLastAccessed,
          [time],
        ),
        returnValue: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  void setLastAccessedSync(DateTime? time) => super.noSuchMethod(
        Invocation.method(
          #setLastAccessedSync,
          [time],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<DateTime> lastModified() => (super.noSuchMethod(
        Invocation.method(
          #lastModified,
          [],
        ),
        returnValue: _i6.Future<DateTime>.value(_FakeDateTime_7(
          this,
          Invocation.method(
            #lastModified,
            [],
          ),
        )),
      ) as _i6.Future<DateTime>);

  @override
  DateTime lastModifiedSync() => (super.noSuchMethod(
        Invocation.method(
          #lastModifiedSync,
          [],
        ),
        returnValue: _FakeDateTime_7(
          this,
          Invocation.method(
            #lastModifiedSync,
            [],
          ),
        ),
      ) as DateTime);

  @override
  _i6.Future<dynamic> setLastModified(DateTime? time) => (super.noSuchMethod(
        Invocation.method(
          #setLastModified,
          [time],
        ),
        returnValue: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  void setLastModifiedSync(DateTime? time) => super.noSuchMethod(
        Invocation.method(
          #setLastModifiedSync,
          [time],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<_i4.RandomAccessFile> open(
          {_i4.FileMode? mode = _i4.FileMode.read}) =>
      (super.noSuchMethod(
        Invocation.method(
          #open,
          [],
          {#mode: mode},
        ),
        returnValue:
            _i6.Future<_i4.RandomAccessFile>.value(_FakeRandomAccessFile_8(
          this,
          Invocation.method(
            #open,
            [],
            {#mode: mode},
          ),
        )),
      ) as _i6.Future<_i4.RandomAccessFile>);

  @override
  _i4.RandomAccessFile openSync({_i4.FileMode? mode = _i4.FileMode.read}) =>
      (super.noSuchMethod(
        Invocation.method(
          #openSync,
          [],
          {#mode: mode},
        ),
        returnValue: _FakeRandomAccessFile_8(
          this,
          Invocation.method(
            #openSync,
            [],
            {#mode: mode},
          ),
        ),
      ) as _i4.RandomAccessFile);

  @override
  _i6.Stream<List<int>> openRead([
    int? start,
    int? end,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #openRead,
          [
            start,
            end,
          ],
        ),
        returnValue: _i6.Stream<List<int>>.empty(),
      ) as _i6.Stream<List<int>>);

  @override
  _i4.IOSink openWrite({
    _i4.FileMode? mode = _i4.FileMode.write,
    _i14.Encoding? encoding = const _i14.Utf8Codec(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #openWrite,
          [],
          {
            #mode: mode,
            #encoding: encoding,
          },
        ),
        returnValue: _FakeIOSink_9(
          this,
          Invocation.method(
            #openWrite,
            [],
            {
              #mode: mode,
              #encoding: encoding,
            },
          ),
        ),
      ) as _i4.IOSink);

  @override
  _i6.Future<_i9.Uint8List> readAsBytes() => (super.noSuchMethod(
        Invocation.method(
          #readAsBytes,
          [],
        ),
        returnValue: _i6.Future<_i9.Uint8List>.value(_i9.Uint8List(0)),
      ) as _i6.Future<_i9.Uint8List>);

  @override
  _i9.Uint8List readAsBytesSync() => (super.noSuchMethod(
        Invocation.method(
          #readAsBytesSync,
          [],
        ),
        returnValue: _i9.Uint8List(0),
      ) as _i9.Uint8List);

  @override
  _i6.Future<String> readAsString(
          {_i14.Encoding? encoding = const _i14.Utf8Codec()}) =>
      (super.noSuchMethod(
        Invocation.method(
          #readAsString,
          [],
          {#encoding: encoding},
        ),
        returnValue: _i6.Future<String>.value(_i13.dummyValue<String>(
          this,
          Invocation.method(
            #readAsString,
            [],
            {#encoding: encoding},
          ),
        )),
      ) as _i6.Future<String>);

  @override
  String readAsStringSync({_i14.Encoding? encoding = const _i14.Utf8Codec()}) =>
      (super.noSuchMethod(
        Invocation.method(
          #readAsStringSync,
          [],
          {#encoding: encoding},
        ),
        returnValue: _i13.dummyValue<String>(
          this,
          Invocation.method(
            #readAsStringSync,
            [],
            {#encoding: encoding},
          ),
        ),
      ) as String);

  @override
  _i6.Future<List<String>> readAsLines(
          {_i14.Encoding? encoding = const _i14.Utf8Codec()}) =>
      (super.noSuchMethod(
        Invocation.method(
          #readAsLines,
          [],
          {#encoding: encoding},
        ),
        returnValue: _i6.Future<List<String>>.value(<String>[]),
      ) as _i6.Future<List<String>>);

  @override
  List<String> readAsLinesSync(
          {_i14.Encoding? encoding = const _i14.Utf8Codec()}) =>
      (super.noSuchMethod(
        Invocation.method(
          #readAsLinesSync,
          [],
          {#encoding: encoding},
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  _i6.Future<_i4.File> writeAsBytes(
    List<int>? bytes, {
    _i4.FileMode? mode = _i4.FileMode.write,
    bool? flush = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #writeAsBytes,
          [bytes],
          {
            #mode: mode,
            #flush: flush,
          },
        ),
        returnValue: _i6.Future<_i4.File>.value(_FakeFile_3(
          this,
          Invocation.method(
            #writeAsBytes,
            [bytes],
            {
              #mode: mode,
              #flush: flush,
            },
          ),
        )),
      ) as _i6.Future<_i4.File>);

  @override
  void writeAsBytesSync(
    List<int>? bytes, {
    _i4.FileMode? mode = _i4.FileMode.write,
    bool? flush = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #writeAsBytesSync,
          [bytes],
          {
            #mode: mode,
            #flush: flush,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<_i4.File> writeAsString(
    String? contents, {
    _i4.FileMode? mode = _i4.FileMode.write,
    _i14.Encoding? encoding = const _i14.Utf8Codec(),
    bool? flush = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #writeAsString,
          [contents],
          {
            #mode: mode,
            #encoding: encoding,
            #flush: flush,
          },
        ),
        returnValue: _i6.Future<_i4.File>.value(_FakeFile_3(
          this,
          Invocation.method(
            #writeAsString,
            [contents],
            {
              #mode: mode,
              #encoding: encoding,
              #flush: flush,
            },
          ),
        )),
      ) as _i6.Future<_i4.File>);

  @override
  void writeAsStringSync(
    String? contents, {
    _i4.FileMode? mode = _i4.FileMode.write,
    _i14.Encoding? encoding = const _i14.Utf8Codec(),
    bool? flush = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #writeAsStringSync,
          [contents],
          {
            #mode: mode,
            #encoding: encoding,
            #flush: flush,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<bool> exists() => (super.noSuchMethod(
        Invocation.method(
          #exists,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  bool existsSync() => (super.noSuchMethod(
        Invocation.method(
          #existsSync,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<String> resolveSymbolicLinks() => (super.noSuchMethod(
        Invocation.method(
          #resolveSymbolicLinks,
          [],
        ),
        returnValue: _i6.Future<String>.value(_i13.dummyValue<String>(
          this,
          Invocation.method(
            #resolveSymbolicLinks,
            [],
          ),
        )),
      ) as _i6.Future<String>);

  @override
  String resolveSymbolicLinksSync() => (super.noSuchMethod(
        Invocation.method(
          #resolveSymbolicLinksSync,
          [],
        ),
        returnValue: _i13.dummyValue<String>(
          this,
          Invocation.method(
            #resolveSymbolicLinksSync,
            [],
          ),
        ),
      ) as String);

  @override
  _i6.Future<_i4.FileStat> stat() => (super.noSuchMethod(
        Invocation.method(
          #stat,
          [],
        ),
        returnValue: _i6.Future<_i4.FileStat>.value(_FakeFileStat_10(
          this,
          Invocation.method(
            #stat,
            [],
          ),
        )),
      ) as _i6.Future<_i4.FileStat>);

  @override
  _i4.FileStat statSync() => (super.noSuchMethod(
        Invocation.method(
          #statSync,
          [],
        ),
        returnValue: _FakeFileStat_10(
          this,
          Invocation.method(
            #statSync,
            [],
          ),
        ),
      ) as _i4.FileStat);

  @override
  _i6.Stream<_i4.FileSystemEvent> watch({
    int? events = 15,
    bool? recursive = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #watch,
          [],
          {
            #events: events,
            #recursive: recursive,
          },
        ),
        returnValue: _i6.Stream<_i4.FileSystemEvent>.empty(),
      ) as _i6.Stream<_i4.FileSystemEvent>);
}
