// Mocks generated by Mockito 5.4.6 from annotations
// in ai_therapist_app/test/services/voice_service_baseline_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:typed_data' as _i7;

import 'package:ai_therapist_app/data/datasources/remote/api_client.dart'
    as _i4;
import 'package:ai_therapist_app/services/config_service.dart' as _i3;
import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConfigService_1 extends _i1.SmartFake implements _i3.ConfigService {
  _FakeConfigService_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i4.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get httpClient => (super.noSuchMethod(
        Invocation.getter(#httpClient),
        returnValue: _FakeClient_0(
          this,
          Invocation.getter(#httpClient),
        ),
      ) as _i2.Client);

  @override
  _i3.ConfigService get configService => (super.noSuchMethod(
        Invocation.getter(#configService),
        returnValue: _FakeConfigService_1(
          this,
          Invocation.getter(#configService),
        ),
      ) as _i3.ConfigService);

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  bool get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: false,
      ) as bool);

  @override
  _i6.Stream<String> get errorStream => (super.noSuchMethod(
        Invocation.getter(#errorStream),
        returnValue: _i6.Stream<String>.empty(),
      ) as _i6.Stream<String>);

  @override
  _i6.Future<void> updateAuthToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #updateAuthToken,
          [token],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<Map<String, dynamic>> get(
    String? endpoint, {
    Map<String, String>? headers,
    Map<String, dynamic>? queryParams,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [endpoint],
          {
            #headers: headers,
            #queryParams: queryParams,
          },
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> post(
    String? endpoint,
    Map<String, dynamic>? data, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [
            endpoint,
            data,
          ],
          {#headers: headers},
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> put(
    String? endpoint,
    Map<String, dynamic>? data, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [
            endpoint,
            data,
          ],
          {#headers: headers},
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<dynamic> patch(
    String? endpoint, {
    dynamic body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [endpoint],
          {#body: body},
        ),
        returnValue: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  _i6.Future<Map<String, dynamic>> delete(
    String? endpoint, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [endpoint],
          {#headers: headers},
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> uploadFile(
    String? endpoint,
    String? fieldName,
    _i7.Uint8List? fileData,
    String? fileName, {
    Map<String, String>? headers,
    Map<String, String>? additionalFields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadFile,
          [
            endpoint,
            fieldName,
            fileData,
            fileName,
          ],
          {
            #headers: headers,
            #additionalFields: additionalFields,
          },
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<_i7.Uint8List> downloadFile(String? url) => (super.noSuchMethod(
        Invocation.method(
          #downloadFile,
          [url],
        ),
        returnValue: _i6.Future<_i7.Uint8List>.value(_i7.Uint8List(0)),
      ) as _i6.Future<_i7.Uint8List>);

  @override
  void setAuthToken(String? token) => super.noSuchMethod(
        Invocation.method(
          #setAuthToken,
          [token],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearAuthToken() => super.noSuchMethod(
        Invocation.method(
          #clearAuthToken,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setBaseUrl(String? url) => super.noSuchMethod(
        Invocation.method(
          #setBaseUrl,
          [url],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setTimeout(Duration? timeout) => super.noSuchMethod(
        Invocation.method(
          #setTimeout,
          [timeout],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<bool> checkConnection() => (super.noSuchMethod(
        Invocation.method(
          #checkConnection,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<Map<String, dynamic>> callLLMDirect(
    String? systemPrompt,
    String? userMessage, {
    List<Map<String, String>>? conversationHistory,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #callLLMDirect,
          [
            systemPrompt,
            userMessage,
          ],
          {
            #conversationHistory: conversationHistory,
            #additionalParams: additionalParams,
          },
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);
}
